### ISSUE TITLE
[SP2019]Arrange with ECS to cut the wood

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#100]
This will happen Tuesday morning

**Comment by trickeydan** [comment]
@jcwilliamson Are you able to do

**Comment by jcwilliamson** [comment]
I'm currently out of town, and will be for about another week. I may not be
the best person.

**Comment by trickeydan** [comment]
Maybe email them? I thought you would be a good person because they know you from the Motor mounts.

We have a real lack of people at the moment, especially in Southampton

**Comment by jcwilliamson** [comment]
I'm happy to send an email tomorrow. I'll be around at some point next week
(tbd).

**Comment by jcwilliamson** [comment]
Mark Long in the mechanical workshop (59/1241) Has agreed to do this for us.

**Comment by kierdavis** [comment]
Great, thanks Jack :+1:

**Comment by trickeydan** [comment]
I think we can close this ticket now as it has been agreed.
