### ISSUE TITLE
[SP2019]Confirm academic talks

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#102]

**Comment by joe9599** [comment]
I believe Son is doing this

**Comment by tshoang** [comment]
I managed to have confirmation from Denis and Jon. Still looking for a third speaker (probably have to ask Kirk, but he said that he is very busy).

**Comment by trickeydan** [comment]
I've just spoken to Futureworlds and they can probably come if we need them to do a talk. It'd be better to get Kirk if we can though.

**Comment by Adimote** [comment]
Any update on this? @tshoang

**Comment by trickeydan** [comment]
```
Unfortunately, Kirk will be in Kathmandu. I’m going to ask Klaus-Peter as he did some work with swarm robot.
```

@JennyLouise  How would you feel about doing a talk about your research if Klaus is unavailable? It's quite relevant to the students and I think it would be great. No worries if not, or you don't have time to prepare etc

**Comment by tshoang** [comment]
While I do have some positive response from Klaus-Peter, I would encourage/prefer if @JennyLouise can give a talk. That would be great.

**Comment by JennyLouise** [comment]
I can give a talk, when would it be?

**Comment by tshoang** [comment]
@JennyLouise That will be on Tuesday (13th Aug) 9:00--10:00. What will be the title of your talk?

**Comment by JennyLouise** [comment]
@tshoang Something like "Learning in the Deep", about using AUVs and ROVs in the deep sea, and using machine learning and computer vision on the images they collect

**Comment by tshoang** [comment]
@JennyLouise Sounds great. I will update the schedule accordingly.

**Comment by trickeydan** [comment]
I think everything's good here then now? I'll close this issue, but feel free to reopen if there are any problems.
