### ISSUE TITLE
[SP2019]Create programming workshops

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#103]
Typically this is a series of tasks building up from "how to do a for loop" onto moving a robot, onto more complex stuff.

See also #59 for hyper-general thoughts on improvements.

**Comment by joe9599** [comment]
@ninjafrostpn Could you do this again?

**Comment by RealOrangeOne** [comment]
The previous workshops are currently on the docs:

https://docs.sourcebots.co.uk/tutorials/intro-to-python/
https://docs.sourcebots.co.uk/tutorials/python-whirlwind-tour/

They _may_ want some updating, and checking they're still fine, but I suspect they're fine to ship as-is.

(Context: They were written by me)

**Comment by trickeydan** [comment]
The python labs last year had an awful rating and need to be reworked majorly

**Comment by Adimote** [comment]
Looking at the ratings for last year, it seems they forgot to put a question for the programming workshop. However it's worth noting the python workshop was the lowest of all workshops in 2017 (70% vs 72%ish for Mechanical and 74%ish for Electronics), and both other workshops dropped to 71% in 2018

**Comment by RealOrangeOne** [comment]
> The python labs last year had an awful rating

> Looking at the ratings for last year, it seems they forgot to put a question for the programming workshop

umwhut?

I'd be interested in hearing what about the workshops wasn't liked. I ran the workshops in 2017 and 2018. The primary issue was that we didn't have much for those who already knew python besides "Here's a simulator", which isn't really ideal. I don't know what extensions we can do for those who already know python, besides maybe getting them to do some arduino stuff?

**Comment by PeterJCLaw** [comment]
Some thoughts on more advanced things we could extend the programming workshop towards:
- arduino (as mentioned):
  - potentially making use of a sensor which was created in an earlier workshop
  - manually program the arduino to do PWM. Clearly not actually useful, but could be a fun challenge and has obvious output (which I personally find make any challenge more fun)
- some sort of interactive stuff, maybe something like programming traffic lights which respond to the presence of cars (either number of markers shown, or number of micro switches depressed)
- a more interesting debugging challenge which has several layers which need fixing; either directly (many issues at different layers) or as knock-on effects (fixing one issue causes another issue elsewhere that was previously being masked)
- a challenge to create a simulation of their robot in a match -- get them actually writing a state machine and working through the scenarios it needs to support
- writing tests!
  - Possibly as an implementation of the previous idea, but I'd really enjoy seeing more advanced teams having test suites to simulate inputs etc.
  - maybe an introduction to unit-testing? Not necessarily useful for this course, but definitely useful outside it
- explore other good coding practices:
  - breaking code up into re-usable chunks (i.e: functions and maybe different source files)
  - designing for maintenance - choosing which way to slice the logic
  - refactoring & rewriting for clarity as requirements change; I suspect this could be particularly useful if we can find a good way to teach it

I realise some of these are probably _way_ too advanced, though maybe not. IMO it would be great to have a couple of things in this realm ready to go for the more advanced participants.

**Comment by Adimote** [comment]
Two sections: 
- "How to python"
- "How to use the robot API"

**Comment by PeterJCLaw** [comment]
@sedders123 what's the status here? (I'm wondering if this is something I can help with remotely)

**Comment by sedders123** [comment]
So far I've taken a look at the Whirlwind tour that we already have and have been making some minor tweaks throughout. I'm also adding a brief section at the end to cover the robot API (ping @trickeydan 
 what will that look like? SR/sbot/something else? This also affects whether we're using Python 2 or 3).

We've identified the need for some more intermediate and advanced activities, and I also some think some volunteer guidance around what to do when running the lab would be good, as last year there was a lot of just sitting at a table rather than engaging with students. Are you interested in helping with either of these?

In addition to your great list of advanced topics, I thought that maybe we could get them to create a simple quiz game. Could start with an input, an if-else and one question. Then create a function that takes a question and an answer and asks the question returning True/False depending on the result. Then could extend to store questions and answers in a dictionary that is looped through. Then we could show them how to keep track of score (maybe save the high score to a disk?). Then if they want to push themselves we could give them some ideas such as multiple players etc. to implement on their own. Not 100% sure about it as it's not very robot-y but I liked the progression and that they could build on what they've just learnt.

**Comment by PeterJCLaw** [comment]
:+1: to the idea of guidance for volunteers.

Also like the game idea.

**Comment by PeterJCLaw** [comment]
I've started on some mentor guidance at https://docs.google.com/document/d/1QEPMs5okJV5En-WPz5YgHt1_6kkx5C85YV-QP3oswQ0/edit

**Comment by trickeydan** [comment]
> So far I've taken a look at the Whirlwind tour that we already have and have been making some minor tweaks throughout. I'm also adding a brief section at the end to cover the robot API (ping @trickeydan
> what will that look like? SR/sbot/something else? This also affects whether we're using Python 2 or 3).

It should be `sbot` unless something goes very very wrong. I've been stress testing it all morning and it's been good so far. Thus it will be Python 3.7.4 on "SourceOS" (Buster).

I am currently writing the API docs, but I don't think they'll be finished today because I'm tired and have some other things to do also.

> We've identified the need for some more intermediate and advanced activities, and I also some think some volunteer guidance around what to do when running the lab would be good, as last year there was a lot of just sitting at a table rather than engaging with students. Are you interested in helping with either of these?

I don't think this should go on this ticket, but I'd like to see volunteers mentoring teams, like in 2016.

> In addition to your great list of advanced topics, I thought that maybe we could get them to create a simple quiz game. Could start with an input, an if-else and one question. Then create a function that takes a question and an answer and asks the question returning True/False depending on the result. Then could extend to store questions and answers in a dictionary that is looped through. Then we could show them how to keep track of score (maybe save the high score to a disk?). Then if they want to push themselves we could give them some ideas such as multiple players etc. to implement on their own. Not 100% sure about it as it's not very robot-y but I liked the progression and that they could build on what they've just learnt.

I think if we're going to teach them some more advanced programming, we should consider some more advanced principles rather than simply higher complexity code.

**Comment by PeterJCLaw** [comment]
> > So far I've taken a look at the Whirlwind tour that we already have and have been making some minor tweaks throughout. I'm also adding a brief section at the end to cover the robot API (ping @trickeydan
> > what will that look like? SR/sbot/something else? This also affects whether we're using Python 2 or 3).
> 
> It should be `sbot` unless something goes very very wrong. I've been stress testing it all morning and it's been good so far. Thus it will be Python 3.7.4 on "SourceOS" (Buster).
> 
> I am currently writing the API docs, but I don't think they'll be finished today because I'm tired and have some other things to do also.

Does this mean that `sbot`'s API diverges from the existing SourceBots API (other than the change to get the servos on a separate board)? I'd thought a major feature was that the competitor-facing API wasn't changing?

If the API isn't changing, is there a reason we can't use the existing docs?

**Comment by PeterJCLaw** [comment]
> > So far I've taken a look at the Whirlwind tour that we already have and have been making some minor tweaks throughout. I'm also adding a brief section at the end to cover the robot API (ping @trickeydan
> > what will that look like? SR/sbot/something else? This also affects whether we're using Python 2 or 3).
> 
> It should be `sbot` unless something goes very very wrong. I've been stress testing it all morning and it's been good so far. Thus it will be Python 3.7.4 on "SourceOS" (Buster).
> 
> I am currently writing the API docs, but I don't think they'll be finished today because I'm tired and have some other things to do also.

Does this mean that `sbot`'s API diverges from the existing SourceBots API (other than the change to get the servos on a separate board)? I'd thought a major feature was that the competitor-facing API wasn't changing?

If the API isn't changing, is there a reason we can't use the existing docs?

**Comment by kierdavis** [comment]
> Does this mean that `sbot`'s API diverges from the existing SourceBots API

The sbot API doesn't differ semantically from the classic SourceBots API, but there are syntactic differences. For example, `r.motor_board.m0 = 0.5` becomes `r.motor_board.motors[0].power = 0.5`. These changes aim to make the API more consistent as a whole.

**Comment by trickeydan** [comment]
> If the API isn't changing, is there a reason we can't use the existing docs?

We're keeping the same text. However, we need to update them anyway because the kit hardware has changed.

**Comment by PeterJCLaw** [comment]
@Adimote has apparently taken this on.

**Comment by Tyler-Ward** [comment]
@Adimote I assume we can close this now

**Comment by PeterJCLaw** [comment]
The workshops have happened.
