### ISSUE TITLE
[SP2019]Schedule volunteers for competition

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#106]

**Comment by joe9599** [comment]
@Adimote Is this something you could do as part of #127

**Comment by joe9599** [comment]
Oops, just seen you're assigned already

**Comment by Adimote** [comment]
I've done the majority of the work for the Friday now, I don't think its worth scheduling volunteers for the rest of the week as it really should be just that everyone defaults to Lvl 2 labs, unless the cube contingency asks for more people.

Here's the schedule:
https://docs.google.com/spreadsheets/d/1I4kc3PxRiNX85NAW5Gpr84YNtAHk1YM2GYPJRwxmELQ/edit?usp=sharing

**Comment by Adimote** [comment]
I need to get feedback from people as quite a few roles are filled just by people who happened to be free, also there's no head judge right now (because I'm not sure who is owning the rules)

**Comment by trickeydan** [comment]
> I've done the majority of the work for the Friday now, I don't think its worth scheduling volunteers for the rest of the week as it really should be just that everyone defaults to Lvl 2 labs, unless the cube contingency asks for more people.

I'm very concerned about people just drifting over to the cube like last year.

**Comment by Adimote** [comment]
I don't think we need to schedule to stop that, we can just be aware of it and tell cube people to tell extras to go back to the labs

**Comment by trickeydan** [comment]
> I don't think we need to schedule to stop that, we can just be aware of it and tell cube people to tell extras to go back to the labs

I distinctly recall volunteers refusing to return last year when I went over to get them. How can we prevent this from happening again?

**Comment by Adimote** [comment]
We can allocate a 'cube team' who are the only people who can stay at the cube, everyone else must go to the labs and help students unless they're called over for specific tasks

**Comment by Adimote** [comment]
(I guess we can also include this info in a briefing email)

**Comment by kierdavis** [comment]
It would be nice if we could rotate volunteers between labs and the cube, so they can get a taste of both sides of the summer school, and so that no one is stuck in a position they dislike with no opportunity to switch.

Perhaps a good compromise is to have a different "cube team" for each day?

**Comment by trickeydan** [comment]
We need to poll people on what they prefer to do. Some people won't want to be in the cube, or may be unable to do lifting etc. Equally, some may not like labs

**Comment by trickeydan** [comment]
@Adimote what is the status of the schedule?

**Comment by Adimote** [comment]
This is now more-or-less done, there are some on-going tweaks but for now I'm happy for it to be published
