### ISSUE TITLE
[SP2019]Book the after-event meal

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#107]

**Comment by trickeydan** [comment]
Jenny is going to take a poll of attendance and what destinations people are interested in.

Also for te crown on saturday before

Suggestions from the past:

- The Stable
- The Cowherds
- Brewhouse and Kitchen
- Baffi

**Comment by trickeydan** [comment]
@JennyLouise Any updates?

**Comment by trickeydan** [comment]
Jenny is putting a message in slack reminding people to reply. 3pm deadline.

**Comment by JennyLouise** [comment]
We have 18 yeses and 4 maybes, going to book a table of 20 with Baffi. They might need a deposit for a group that large - how are we handling that?

**Comment by JennyLouise** [comment]
We've been asked to give a pre-order for food, including starters and desserts. Will have to put together some kind of google form for people to give us their options

**Comment by JennyLouise** [comment]
https://forms.gle/ZBHifm2ncaCpe8yN6

**Comment by RealOrangeOne** [comment]
We ate, it was good.
