### ISSUE TITLE
[SP2019]Plan cleanup day (Saturday)

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#108]

**Comment by joe9599** [comment]
This seems like a duplicate of #139

**Comment by trickeydan** [comment]
Duplicater

**Comment by RealOrangeOne** [comment]
This is actually for the weekend after, rather than tearing down the arena venue.

**Comment by trickeydan** [comment]
We need to enumerate tasks and assign them to a milestone

**Comment by Tyler-Ward** [comment]
done
