### ISSUE TITLE
[SP2019]Check how many volunteers will attend the Formal meal

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#109]
This can probably be in a form sent at the same time as #105

**Comment by JennyLouise** [comment]
When and where is the formal meal?

**Comment by sedders123** [comment]
According to the schedule (#110) it is in the B38 Terrace Restaurant on Thursday 15th 19:30 till 21:00 (though there are drinks beforehand from 19:00).

**Comment by JennyLouise** [comment]
Thanks, I'll send an email reminding people about the after-event meal #107 and allowing people to sign up for the formal meal

**Comment by trickeydan** [comment]
@JennyLouise Any updates?

**Comment by Adimote** [comment]
Form will be sent out in #105

**Comment by trickeydan** [comment]
This was sorted by me
