### ISSUE TITLE
[SP2019]Confirm Schedule

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#110]

**Comment by trickeydan** [comment]
[309.docx](https://github.com/sourcebots/tasks/files/3396808/309.docx)

**Comment by kierdavis** [comment]
[309.pdf](https://github.com/sourcebots/tasks/files/3397014/309.pdf)

PDF version, courtesy of Google Drive

**Comment by trickeydan** [comment]
[Draft Programme 2019- IN PROGRESS_v2(SH).docx](https://github.com/sourcebots/tasks/files/3439501/Draft.Programme.2019-.IN.PROGRESS_v2.SH.docx)

As a result of #146, we have a slightly more up to date version.

**Comment by trickeydan** [comment]
[Draft Programme 2019- IN PROGRESS_v3(SH).docx](https://github.com/sourcebots/tasks/files/3468944/Draft.Programme.2019-.IN.PROGRESS_v3.SH.docx)

**Comment by andybusse** [comment]
Milestones have gone from this, will make sure they're at least mentioned at intro and drilled into everyones consciousness
As a reminder:
* Monday - Robots designed and send to mech workshop
* Tuesday - First Movement
* Wednesday - Intelligent Movement
* Thursday - Move to Cube
