### ISSUE TITLE
[SP2019]Book car parking for parents

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#112]
Some volunteers may also want parking

**Comment by RealOrangeOne** [comment]
> Some volunteers may also want parking

Volunteer parking is a must have, and probably deserves its own ticket.

Volunteers in accommodation can park there, but it's any which are traveling in which may want some. Alternatively, allocating budget to reimburse parking may be a simpler implementation

**Comment by tshoang** [comment]
I have asked Smallpeice to check with Hospitality. Can I know the rough number of parkings necessary for  the volunteers?

**Comment by trickeydan** [comment]
According to the volunteer list, there are currently two `Maybe` and one definitely needing parking.

Of those, two have requested accomodation, so shiuld have parking there.

@RealOrangeOne are there more people than I know about?

**Comment by RealOrangeOne** [comment]
I have no idea who needs parking, all I know is that _I_ need it. 

Considering the maximum number of people who requested and need parking is 3, It's probably fine to ensure there's at least 3 spaces. I'd be surprised if requiring an extra space or 2 at halls is going to be a massive inconvenience.

Generally parking is just handled by halls, but I don't know if that's something we need to pre-allocate, or if simply informing them they have a car is enough (that's what I did last year)

**Comment by tshoang** [comment]
I have asked Hospitality for 3 parking spaces, most likely will be in Avenue Campus.

**Comment by Adimote** [comment]
Just checking, was parking for parents also booked? It seems most of the conversation on this issue is volunteer parking (especially around the 3 spaces)

**Comment by tshoang** [comment]
Yes, the parents parking was also booked. Just remind me that the 3 parking spaces is for the whole week where the parents parking was only for Friday.
