### ISSUE TITLE
[SP2019]Plan Rules Q&A session

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#113]
We need to plan a slot early in the week (likely not the first day though) where the competitors can ask questions about the rules.
This likely happens during a robot hacking slot, or a similar lab.

We'll need to ensure that the head judge is around for this session.

**Comment by Adimote** [comment]
This is a talk by the head judge on one of the later days

**Comment by RealOrangeOne** [comment]
We can implement this by running a Q&A session inside one of the robot hacking sessions. The most likely period is 15:50-16:30.

We can implement this by giving teams some warning to prepare questions, and then get them around 1 area to ask questions. The large table in L3 labs would work well for this!

This doesn't _strictly_ need to be 15:50. It mostly depends when people who know the rules are around. We can likely play this by ear, so i'm moving it to something we can plan during the week.

**Comment by RealOrangeOne** [comment]
This doesn't appear to be needed anymore as a dedicated session.

Teams can ask questions during the late-night robot hacking, or at a dedicated slot in #136.
