### ISSUE TITLE
[SP2019]Create film and photography plan

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#114]

**Comment by joe9599** [comment]
University photographer may be coming

**Comment by trickeydan** [comment]
Jenny is going to ask Joyce if she is able to book the uni photographer.

Fallback plan is volunteers take photos on phones or maybe Laurie.

**Comment by kierdavis** [comment]
I think at least a couple of our volunteers have cameras - it might be worth sending communication round to see if anyone is interested in bringing theirs and taking some photos.

**Comment by JennyLouise** [comment]
I've been told to email feps-marketing@soton.ac.uk to organise an ECS photographer visit and/or news story. We should make more plans for photography than that, but it's a start

**Comment by jcwilliamson** [comment]
Do we need to arrange media consent for this? Or has the trust handled that.

**Comment by trickeydan** [comment]
Media consent for students is handled, and will be covered in the volunteer briefing at the start of the week.

Media consent for volunteers was covered by the signup form.

**Comment by trickeydan** [comment]
I don't think there is much more for me to do on this.

**Comment by trickeydan** [comment]
We think this is all done.
