### ISSUE TITLE
[SP2019]Flash USB drives with relevant software

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#116]
Every participant gets a USB stick with a basic robot program on it (e.g. hello world or drive forwards).

Also, we need arena zone USBs. The particular contents of these depends on what kit we ship.

**Comment by RealOrangeOne** [comment]
What software is required on USB drives?

**Comment by kierdavis** [comment]
Usually every participant gets a USB stick with a basic robot program on it (e.g. hello world or drive forwards).

Also, we need arena zone USBs. The particular contents of these depends on what kit we ship.

Anything else?

**Comment by Adimote** [comment]
This year teams won't get a USB stick each, there are a bunch of nice-to-have's

**Comment by trickeydan** [comment]
They need to be FAT32 formatted.

**Comment by trickeydan** [comment]
We have the USB drives.

**Comment by RealOrangeOne** [comment]
The drives must be FAT, but they don't need any special software.

**Comment by kierdavis** [comment]
A nice-to-have would be to put a barebones `main.py` on them to make it clearer to the competitors where to put their code.

**Comment by kierdavis** [comment]
This might be useful: https://github.com/kierdavis/flashusb

**Comment by Adimote** [comment]
I have an 8 port usb hub, I'll bring it

**Comment by Adimote** [comment]
Sadly I can't bring the usb hub until Monday because my flight was cancelled :(

**Comment by kierdavis** [comment]
@Adimote No worries, I can just nest four-port hubs :)

**Comment by kierdavis** [comment]
I have flashed 32 robot USBs (2 per team) and 8 arena USBs (2 per zone).
