### ISSUE TITLE
[SP2019]Test software

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#120]

**Comment by trickeydan** [comment]
Can we clarify the difference between this and #118 ?

**Comment by kierdavis** [comment]
Maybe this is referring to non-kit software e.g. srcomp?

**Comment by trickeydan** [comment]
It works. I'm going to leave this open for now as there is more testing I want to do.

**Comment by trickeydan** [comment]
Further robustness testing of ultrasound is required, but the kit is good to ship.

Downgrading this ticket.
