### ISSUE TITLE
[SP2019]Pack sensor kit for team kits

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#121]

**Comment by RealOrangeOne** [comment]
If we don't do this, we need a plan for the alternative.

**Comment by joe9599** [comment]
Is the alternative not just put the sensors into the team kits rather than put them in a sensor kit in a team kit

**Comment by trickeydan** [comment]
Another alternative that has been discussed is just putting them in the middle of the table in labs, like usual.

**Comment by Tyler-Ward** [comment]
packed
