### ISSUE TITLE
[SP2019]Arrange for transportation tools

### ISSUE THREAD

**Issue by JennyLouise** [sourcebots/tasks#124]
Trolleys, etc

**Comment by joe9599** [comment]
Email ECS for trolley

**Comment by Adimote** [comment]
About to send an email to Dave Oakley asking about Trolleys

**Comment by Adimote** [comment]
Prodded Dave Oakley because he's terrible at replying to emails

**Comment by Adimote** [comment]
didn't mean to close.

**Comment by Adimote** [comment]
I'm interpreting 'Transportation Tools' as the ECS powered trolley, is there anything else we need?

**Comment by trickeydan** [comment]
@Adimote any update?

**Comment by trickeydan** [comment]
@RealOrangeOne says that he has a car.
