### ISSUE TITLE
[SP2019]Plan what will be moved by estates

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#125]
We need to sort things into 'move to cube', 'stay in lvl 4', 'stay in labs', etc..

#95 exists to arrange for the moving to happen; this ticket is about planning what should be moved.

**Comment by trickeydan** [comment]
We should base this off the SR lists

**Comment by trickeydan** [comment]
https://docs.google.com/spreadsheets/d/13jDdRkZxgKdROVau9VaZiKZbiDV34_rlcZhWcpzQZO8/edit#gid=0

**Comment by Dasepho** [comment]
Much of the sheet is hidden and I'm not privileged or competent enough to access the rest of it. I'm also unsure whether everything needed for SR is needed for SP too?

**Comment by trickeydan** [comment]
@RealOrangeOne

**Comment by RealOrangeOne** [comment]
The filter on the sheet has now been removed.

**Comment by Dasepho** [comment]
I've looked through the speadsheet, but I don't know where anything currently is or where it should go. Can someone with experience of moving kit help / take this task?

**Comment by Adimote** [comment]
I can help, it seems the sheet has a 'current location' and 'end location' column, so it should be easy to figure out where things are and should go?

**Comment by Adimote** [comment]
Ah I see, the sheet is for the other competition, derp.

**Comment by WillB97** [comment]
also this sheet was last updated when the boxes were moved to level 1 CLS so many of the locations and owners probably want to be updated

**Comment by WillB97** [comment]
Would it be worth creating a copy of this sheet so that it can be preserved for future SR competitions?

**Comment by Adimote** [comment]
Yes

**Comment by WillB97** [comment]
New sheet: https://docs.google.com/spreadsheets/d/1D0pRR4PgVsid5xM-ZgDypfciSpfjOW1VJMAfNDONeQg/edit?usp=sharing

**Comment by Adimote** [comment]
can you give access? I can move it into the SourceBots folder so most people get it too.

**Comment by Adimote** [comment]
@Dasepho Can you please fill the above sheet with your knowledge of the locations of things? You'll know a lot more than me when it comes to the current state of things

**Comment by Dasepho** [comment]
Unfortunately my knowledge of the locations of things is pretty poor. I'm not in Soton to check where things are and this is my first smallpiece so I don't know which things are supposed to go to the cube / bar 2 / bar 3(?) / zepler level 2 / level 3 / anywhere else.

**Comment by Adimote** [comment]
Unassigned myself because it's hard to help out with this remotely

**Comment by sedders123** [comment]
We now have a pile of stuff in L4 to be moved by estates to the cube, as well as the wood from the cupboard. 

The majority of items destined for labs have been moved by volunteers today and the remaining few items will be carried down as needed by volunteers.

**Comment by kierdavis** [comment]
For the record, we didn't book the university porters at all during packdown. This was because they only do moves during working hours, meaning that the earliest opportunity that we could arrange a move would be the following Monday (when almost all of the volunteers would already have gone home). Instead we moved everything using cars, trolleys, and a repurposed piece of stage decking (which happened to be pretty much the right size for our large sheets of hardboard) which worked pretty well.
