### ISSUE TITLE
[SP2019]Create volunteer roles document

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#126]

**Comment by joe9599** [comment]
@Adimote Is this something you could do

**Comment by trickeydan** [comment]
This was done

**Comment by kierdavis** [comment]
For future reference, it looks like this ended up in the ["Role Descriptions" tab of the volunteer schedule](https://docs.google.com/spreadsheets/d/1I4kc3PxRiNX85NAW5Gpr84YNtAHk1YM2GYPJRwxmELQ/edit#gid=1205504208).
