### ISSUE TITLE
[SP2019]Create interactive volunteer schedule

### ISSUE THREAD

**Issue by JennyLouise** [sourcebots/tasks#127]
Google calendar?

**Comment by joe9599** [comment]
@Adimote Could you do this?

**Comment by Adimote** [comment]
Don't think I can make an interactive schedule, I can for sure export it to an auto-updating webpage

**Comment by trickeydan** [comment]
> Don't think I can make an interactive schedule, I can for sure export it to an auto-updating webpage

Relevant: #80

**Comment by RealOrangeOne** [comment]
This is now done, just needs distributing
