### ISSUE TITLE
[SP2019]Prepare forms for borrowed equipment

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#129]

**Comment by kierdavis** [comment]
@Tyler-Ward am I right in thinking that you've made some of these before for previous Smallpeice/SR events?

**Comment by Tyler-Ward** [comment]
https://drive.google.com/file/d/1bIqLW41hUx7TAUbGBkqpm8-Wm7t4GAqs/view?usp=sharing
https://docs.google.com/spreadsheets/d/17fCCiSf0lpQW2PAJGrbuKJUyFhOQsftT/edit#gid=2038790835

**Comment by trickeydan** [comment]
I think it's probably good enough to just reuse those.

This should probably be added to #115

**Comment by kierdavis** [comment]
> This should probably be added to #115

Done.

**Comment by trickeydan** [comment]
I think we can safely close this as long is it is printed, which is tracked elsewhere.
