### ISSUE TITLE
[SP2019]Print signage

### ISSUE THREAD

**Issue by JennyLouise** [sourcebots/tasks#135]

**Comment by JennyLouise** [comment]
Duplicate of #115

**Comment by RealOrangeOne** [comment]
Re-opening, as it needs designing

**Comment by RealOrangeOne** [comment]
- Toilet Locations
- Entrances
- Exits
- Do Not Enter
- Robot Uprising In Progress

**Comment by JennyLouise** [comment]
https://docs.google.com/presentation/d/1sgwSwAuWWEBkRg7AhtbDsDof-JQ-MAZbPSMh3EEs9E0/edit?usp=sharing

Made a start to signage with the locations listed on the schedule - adding the sourcebots or sro logo would be nice, and any missing locations or other signs.

I'll print multiple copies, and will add arrows with a sharpie in whatever directions are needed as we put the signs up

**Comment by trickeydan** [comment]
Interesting idea: Do we want to use the A-frame signs?

**Comment by JennyLouise** [comment]
Signage is printed, a few have gone up already, the rest are in the cube with some blue tack and sharpies
