### ISSUE TITLE
[SP2019]Plan competition intro sequence

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#136]
This is the welcome to the competition (9am on the Friday) for the competitors.
This is when they first see the arena.

**Comment by joe9599** [comment]
@RealOrangeOne @Tyler-Ward Can one of you take this task

**Comment by RealOrangeOne** [comment]
For context, what is this tracking? Is this the talk we do when teams are first taken into the cube?

**Comment by trickeydan** [comment]
> Is this the talk we do when teams are first taken into the cube?

I believe so.

**Comment by RealOrangeOne** [comment]
Look like this is the "SourceBots: Competition Briefing" talk at 9am on Friday. I've also covered doing something on Thursday morning, when teams are first shown the cube.

https://hackmd.io/@cip1G_wQS4mr8THvluJvlQ/Hk9pZOifr/edit

Review appreciated.

**Comment by Dasepho** [comment]
Looks ok to me

**Comment by RealOrangeOne** [comment]
The plan has been finalised with the above plan, and adapted for the truss arena
