### ISSUE TITLE
[SP2019]Design certificates and award cards

### ISSUE THREAD

**Issue by JennyLouise** [sourcebots/tasks#137]

**Comment by joe9599** [comment]
@ninjafrostpn Could you do this again this year?

**Comment by JennyLouise** [comment]
Does anyone have a picture of last year's certificates? What info do we need on there? I've made a simple certificate border, just got to finalise the content on it

**Comment by ninjafrostpn** [comment]
Sorry, yes, I have code and pdfs and things associated with this from last year, so can find these things (and take this if required, as I'm not yet assigned anything, having not interacted with proceedings as of yet), apologies for the silence.

**Comment by ninjafrostpn** [comment]
Found the repository in question here:
https://github.com/sourcebots/art/tree/certificate-2018

**Comment by JennyLouise** [comment]
Nice, I'm happy to leave the designing to you if you want, I can just print them. I'm hoping to print most stuff the weekend before the kids arrive, but can do the certificates later in the week

**Comment by Tyler-Ward** [comment]
For info the we have ordered A4 card stock for the certificates and will be using white postal envelopes for the awards presentation cards which will want printing on and on the cards inside which we can cut out of the A4 sheets.

**Comment by JennyLouise** [comment]
@ninjafrostpn are you okay taking over the design task?

**Comment by trickeydan** [comment]
https://github.com/sourcebots/art

**Comment by trickeydan** [comment]
Date needs updating, otherwise good

**Comment by trickeydan** [comment]
Dan is going to have a look at this.

**Comment by Dasepho** [comment]
cert-gen.py seems to be windows-specific? I might not be much help if that's the case

**Comment by trickeydan** [comment]
> cert-gen.py seems to be windows-specific? I might not be much help if that's the case

Can confirm it currently is, however it should be modifiable pretty easily. Up for a challenge @Dasepho? Feel free to slack me for help / hints

**Comment by Dasepho** [comment]
Challenge accepted, please see slack :smiley:

**Comment by joe9599** [comment]
I have windows, so can try this if you want

**Comment by Dasepho** [comment]
Don't worry. I stopped it being windows software and made it start being linux software :laughing:

**Comment by trickeydan** [comment]
:roll_eyes: I'll make it cross platform if I get a chance.

**Comment by Dasepho** [comment]
I've got it all working now, and have updated year and sponsors so I will be ready to generate all the certificates pending a csv with participants names+schools.
Sample:
![Screenshot at 2019-07-31 14-13-27](https://user-images.githubusercontent.com/47758255/62214669-6f4c0080-b39d-11e9-8e66-7be52063146d.png)

**Comment by Dasepho** [comment]
Going to call this task done and just have #138  to do now
