### ISSUE TITLE
[SP2019]Print award cards and certificates

### ISSUE THREAD

**Issue by JennyLouise** [sourcebots/tasks#138]
Generate the certificates and get them printed. Intentionally separate from #115 as this happens much later in the week and is a bit more involved in terms of preparation.

- [x] Prepare the certificate generation
- [ ] Get the user/team/school datas (CSV)
- [ ] Print the certificates

**Comment by JennyLouise** [comment]
Do we need these on fancy paper?

**Comment by trickeydan** [comment]
I think it'd be nice to have them on decent paper or card. I believe we've ordered 500 sheets of card, which should include enough for that.

I recall issues with the card in the isolutions printers last competition. @RealOrangeOne Are you able to confirm this issue?

**Comment by joe9599** [comment]
We did have problems printing on card in L2, for SR but I think we found a setting that worked

**Comment by RealOrangeOne** [comment]
> I recall issues with the card in the isolutions printers last competition

The issue was more around the speed at which you print. Either you print 1 page at a time, or you slow the print settings down so it prints each page slower.

All the token markers for SR were printed with ECS printers, and they came out fine!

**Comment by Dasepho** [comment]
I can generate all the certificates with this year's sponsors etc once I have the .csv with competitors' names and schools

**Comment by JennyLouise** [comment]
If someone (@Dasepho ?) could generate the general "thanks for participating" certificates, I can print those out this evening.

For the actual prize winners, can someone let me know what time those will be known on friday, I'll make sure to be on highfield and ready to print those on the day.

**Comment by Dasepho** [comment]
We currently don't have team allocations, so if we need to put team names on certificates we'll have to wait until Monday. Personally I would prefer to print them today, i.e. print them without team names if people are happy with that?

I also need to have access to the list of competitors' names to be able to generate them. Can I be given access or (for GDPR reasons) can someone who has that data give it to me on a temporary basis in person this afternoon?

I'd also like to confirm the awards we're doing; is it:
- participation
- 1st, 2nd, 3rd place
- volunteers' choice

**Comment by Dasepho** [comment]
![Screenshot at 2019-08-11 11-39-39](https://user-images.githubusercontent.com/47758255/62832883-55c47780-bc2d-11e9-838b-34644bb8e1b3.png)
![Screenshot at 2019-08-11 11-40-54](https://user-images.githubusercontent.com/47758255/62832885-578e3b00-bc2d-11e9-927b-f74d493aeb2a.png)
![Screenshot at 2019-08-11 11-41-25](https://user-images.githubusercontent.com/47758255/62832886-5826d180-bc2d-11e9-94b2-45255f57ca1a.png)
![Screenshot at 2019-08-11 11-42-01](https://user-images.githubusercontent.com/47758255/62832887-5957fe80-bc2d-11e9-8043-79e79fe51523.png)
![Screenshot at 2019-08-11 11-42-41](https://user-images.githubusercontent.com/47758255/62832888-5a892b80-bc2d-11e9-8a8c-133bd5adfd3a.png)

These are the current designs. Please tell me if they are ok

**Comment by Dasepho** [comment]
Updated "Facilitator's award"
![Screenshot at 2019-08-11 14-09-37](https://user-images.githubusercontent.com/47758255/62834276-cf666080-bc41-11e9-8e5f-917983539d3c.png)

**Comment by JennyLouise** [comment]
Tyler has just mentioned smallpiece provide participation certificates. @trickeydan can you confirm this with them tomorrow? I'll hold off on printing certificates for now.

**Comment by RealOrangeOne** [comment]
@JennyLouise printed the certificates, and hand-wrote award cards.
