### ISSUE TITLE
[SP2019]Find a speaker/presenter for the post finals talk

### ISSUE THREAD

**Issue by JennyLouise** [sourcebots/tasks#140]

**Comment by joe9599** [comment]
Will this be the same speaker as #60

**Comment by joe9599** [comment]
Being sorted by Son

**Comment by RealOrangeOne** [comment]
I'm happy to handle the finals presentation from our side (i'll make sure I have a lot more practice than last time!).

**Comment by tshoang** [comment]
Paul Lewin has agreed to give the closing address and presentation of prizes.
