### ISSUE TITLE
[SP2019]Have meeting with SUSU

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#141]

**Comment by trickeydan** [comment]
Email sent by Jenny to SUSU to setup a date

**Comment by JennyLouise** [comment]
I sent an email to events@susu.org but haven't got a response yet

**Comment by JennyLouise** [comment]
@Tyler-Ward do you have a better email address for me to get ahold of the right people in susu?

**Comment by sedders123** [comment]
Things marked as needed:
 - Fire Extinguishers
 - Scaff grounding
 - Large TV's (Score Display)
 - Audio Mixing Desk
 - Effects Lighting
 - Lighting Desk
 - PC Audio Feed
 - Wash Lighting
 - Wireless Mics
 - Confetti Cannons
 - Rope Barriers
 - Tables + Chairs
 - Power Ditribution
 - Big Fans

**Comment by Tyler-Ward** [comment]
Also see https://docs.google.com/document/d/10Pwl5OvKiICGMxnMQKb0tLM4-nDNfglDuNqyYCCsGYU/edit for the cube hit hire list

**Comment by WillB97** [comment]
What's the stage deck being ordered for?

**Comment by trickeydan** [comment]
> What's the stage deck being ordered for?

See #38

**Comment by trickeydan** [comment]
@Adimote is going to phone tomorrow

**Comment by Adimote** [comment]
I've got the facebook details for the guy in charge of tech, will contact him. We still need to arrange for catering however so don't consider this closed

**Comment by Adimote** [comment]
We've arranged a meeting with him on Friday at 7pm, probably safe to assume it's in the events office on the top floor of the red brick building, but I'll confirm

**Comment by Adimote** [comment]
Location will be Meeting room 7, opposite the lift in stags on level 1

**Comment by trickeydan** [comment]
Done! :tada:
