### ISSUE TITLE
[SP2019]Worksheets for Python Labs

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#143]
Given https://github.com/sourcebots/tasks/issues/103#issuecomment-511142183, do we need worksheets?

_Originally posted by @RealOrangeOne in https://github.com/sourcebots/tasks/issues/92#issuecomment-511142317_

**Comment by kierdavis** [comment]
I think previously we've just asked them to work through Whirlwind Tour and Codecademy. Do we need anything more than that?

**Comment by kierdavis** [comment]
Hang on, what's the difference between this issue and #103?

**Comment by RealOrangeOne** [comment]
Also, why is there a separate issue tracking _whether_ we need worksheets? Seeing as #92 is done, surely this is too?

**Comment by trickeydan** [comment]
Determined that we do. See #103

**Comment by Adimote** [comment]
I'll close this as it's basically a duplicate of #103
