### ISSUE TITLE
[SP2019]Robot building presentation (Monday morning, part of the intro)

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#144]
We typically have a presentation on 'how to build your robot', which includes safety, tips, and tricks.

This is part of the SourceBots intro presentation on the Monday, which is scheduled to last an hour

**Comment by Adimote** [comment]
Andy Busse says he's up for doing this, I think the entire presentation needs a bit clearer scheduling however. It's a 1hr slot, so we need to make sure we fill it.

**Comment by trickeydan** [comment]
I can't find a Github account for Andy, I'm guessing that he isn't in the org?

**Comment by Adimote** [comment]
Invited him now,

//TODO add @andybusse to this

**Comment by RealOrangeOne** [comment]
I've looked at the schedule, and the "How to build your robot" presentation is what's defined in the schedule, so is actually a "Must".

#131 also needs to be handled in the same presentation. Whether this is done by the same person / people, I don't know. I'm happy to do any / all parts if needed :+1:

**Comment by RealOrangeOne** [comment]
I've started basic work on this presentation, and put it in the smallpeice directory.

It's currently very closely based on the SR2019 kickstart presentation, but with things which aren't applicable removed.

It's the same presentation as the game (#131), so I can't share the link publicly.

**Comment by andybusse** [comment]
Hi folks.
I'll dig out what I did last year and coordinate who's doing what with Jake.
Some of it's not going to be in slides anyway.

**Comment by PeterJCLaw** [comment]
This happened.
