### ISSUE TITLE
[SP2019]Get USB Sticks

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#145]
Joyce doesn't have any ECS USB Sticks this year, so we need to go buy some. These are preferably branded, but if it's expensive we can just stick with cheap unbranded ones.

**Comment by trickeydan** [comment]
We will have ~40 USB Sticks already.

**Comment by Adimote** [comment]
Cool, so we need to order 50ish more so every student has one, assuming we want to have one each?

**Comment by Adimote** [comment]
Marking this 'SHOULD' as we can handle running a summer school with 40 sticks

**Comment by kierdavis** [comment]
Does the closure of this issue mean that we've ordered more USB sticks, or that we've decided we're going to run with just the ones we've already got?

**Comment by trickeydan** [comment]
We're going to run with the current ones
