### ISSUE TITLE
[SP2019]Work out venue layout

### ISSUE THREAD

**Issue by joe9599** [sourcebots/tasks#149]

**Comment by joe9599** [comment]
We need to work out the layout for the competition, it would be very tight if even possible to have 16 teams, help desk and front/welcome/reception desk (as well as somewhere for volunteers and supervisers to have a break, or just be when not needed) all in bar 2, so we almost certainly need to book level 3,

**Comment by joe9599** [comment]
We should try and get this figured out on saturday

**Comment by trickeydan** [comment]
![image](https://user-images.githubusercontent.com/7862359/61995991-1f142c00-b087-11e9-88b3-e6cbf49f5fa7.png)

Based on this, but:

- move the teams near the stairs to the area by the large fire escape (not in the red area), replacing that area with helpdesk / reception. 
- Don't mark out pit boundaries
- Possibly make a testing area top right corner of the cube
- Encourage teams to use Bar 3 / outside area for dev if needed (weather permitting)

The game _may_ be a 4-robot game, so we should have more tinker time available to teams, also.

**Comment by trickeydan** [comment]
Ok, so I think @RealOrangeOne used my account to comment the above. Please pass queries to him, not me :P

**Comment by trickeydan** [comment]
I think this has been worked out enough to no longer be blocking. A decent map is definitely a separate issue
