### ISSUE TITLE
[SP2019]Sort out the arena

### ISSUE THREAD

**Issue by RealOrangeOne** [sourcebots/tasks#150]
Related to #63. If we can't get scaffolding, we need a backup. 

SR have a wooden arena which could work, but we'd need to ask for it (likely as part of #8 )

**Comment by trickeydan** [comment]
@RealOrangeOne Please could you add some more information on what this ticket is about?

**Comment by WillB97** [comment]
For putting the carpet down, it would be useful to have a roll of gaffa tape of a similar colour to the carpet to cover the seam.

**Comment by trickeydan** [comment]
Our budget closes at midnight, this probably won't be possible. @RealOrangeOne @scorpia any ideas?

**Comment by trickeydan** [comment]
@WillB97 is apparently going to sum up truss and check SUSU's scaff on Tuesday.

I'm assigning this to Will until we know more details.

**Comment by Adimote** [comment]
We should have a plan B, I'm happy to speak to SR and get a verbal agreement to borrow their wooden arena. We'd need to ensure we rent a van to ship it to/from the SR container (this can happen at the same time as picking up kits) and find a plan for mounting screens and optionally holding back visitors.

**Comment by WillB97** [comment]
I agree it would be worth picking up the SR arena along with the kits as a fallback plan.

**Comment by Adimote** [comment]
Okay so the main plan right now is to work with the SR arena, with the SUSU arena as plan B and the £645 company as plan C.

Peter highlighted these issues with building the SR arena, I'll answer them inline
- build crowd barriers
  - Hills Road ran with rope crowd barriers for their arena just fine, SUSU has likely enough crowd barriers to cover 2 edges of the SR arena.
- find a mounting situation for the screens
  - an MVP competition will work without these screens, we can use the projection booth.
- work out how to transport it
  - We can rent a van for ~£100
- Work out how to assemble it
  - That can be done during the week with advice from Rich, I believe the method of attaching is by screws.
- work out if it even fits in the Cube (previous deployments of it have had a 10x10m footprint, not the 8x8 we're used to for scaff)
   - Without corner screens, we can move the crowd barriers to right next to the wooden walls, which saves a lot of space. We mapped it out, and with those modifications it easily fits.

**Comment by WillB97** [comment]
The current SUSU arena design (8.4m x 8.4m internal) is:
![Screenshot 2019-08-03 at 12 29 56](https://user-images.githubusercontent.com/10937272/62412408-aae30680-b5f9-11e9-905e-c90d09b0f17f.png)
this only uses truss available to SUSU as we're a bit close for getting a quote for additional truss.

- 4x 2-way truss corners (H30V-C003)
- 16x 2m truss (H30V-L200)

**Comment by Adimote** [comment]
That seems pretty good! One big question to solve with the SUSU plan will be how to mount markers onto the truss

**Comment by WillB97** [comment]
attach the hardboard to the inner edge of the truss, you can also set the wall height by how much you have the board above the top edge of the truss

**Comment by Adimote** [comment]
**We're going for the SUSU arena design**, as I haven't managed to get any reasonable quotes from scaff companies.

**Comment by trickeydan** [comment]
This seems to have been sorted now and Josh and Will said they had it in hand earlier.
