### ISSUE TITLE
[SP2019]Order List 6 🔥

### ISSUE THREAD

**Issue by sedders123** [sourcebots/tasks#152]
- [x] 18L RUBs
- [x] Servo Boards
- [x] Cardboard
- [x] Drills
- [x] Drill Batteries
- [x] Drill Battery Chargers
- [x] Folding Boxes/Crates
- [x] Radios (@trickeydan has acquired an invoice)
- [x] T-Shirts
- [ ] Desk Fan
- [x] [Copper Tape](https://www.amazon.co.uk/10mm-20mm-Copper-Slug-Tape/dp/B01G971VGY/ref=sr_1_7?keywords=copper+tape&qid=1564246595&s=gateway&sr=8-7)
- [x] [Coloured stickers](https://www.amazon.co.uk/dp/B076NQL6HK/ref=psdc_200903031_t1_B01KJ0E10A)

**Comment by trickeydan** [comment]
All orders sent.

I don't know where there is a desk fan on here..
