### ISSUE TITLE
[SP2019]Create score-entry mechanism

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/tasks#153]
We need:
- [x] paper sheets for recording the game-state after each match https://github.com/sourcebots/compstate-smallpeice2019/pull/3
- [x] updates to the score-entry UI to match https://github.com/PeterJCLaw/srcomp-scorer/pull/3
- [x] a data format for the compstate https://github.com/sourcebots/compstate-smallpeice2019/pull/1

**Comment by trickeydan** [comment]
@PeterJCLaw This is blocked on #81, but are you able to work on this?

**Comment by PeterJCLaw** [comment]
I'm not sure this is blocked on the rules per-se, as long as we're certain about what the game is and how the scoring works then I think this can progress.

**Comment by trickeydan** [comment]
We'll be much more certain on the exact details of the game on Saturday, as @RealOrangeOne plans to write them then I believe

**Comment by PeterJCLaw** [comment]
This is underway at https://github.com/PeterJCLaw/srcomp-scorer/compare/sr2019...smallpeice-2019 (ignore the base branch)

**Comment by PeterJCLaw** [comment]
https://github.com/PeterJCLaw/srcomp-scorer/pull/3 now exists for review of the score-entry UI.

**Comment by PeterJCLaw** [comment]
This is done.
