### ISSUE TITLE
[SP2019]Storage charge batteries

### ISSUE THREAD

**Issue by Tyler-Ward** [sourcebots/tasks#157]

**Comment by RealOrangeOne** [comment]
This was _mostly_ done, however there are almost certainly other batteries which need storage charging. 

These batteries are stored separately, so should be easy to do when needed.

**Comment by kierdavis** [comment]
Did we label which box was which (storage charged vs not storage charged)?

**Comment by RealOrangeOne** [comment]
I thought we did? Although I never saw any labelling myself.

**Comment by kierdavis** [comment]
Oh, actually it should be easy to identify - the ones that have been storage charged are in bags while the ones that are not storage charged are loose.

**Comment by trickeydan** [comment]
This was done
