### ISSUE TITLE
[SP2019]plan mech parts order

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#16]

**Comment by kierdavis** [comment]
What makes this different to #17?

**Comment by jcwilliamson** [comment]
As far as I'm aware, the main difference here is how easily we can store the two. Ordering the bigger stuff closer to the competition makes dealing with storage less of a problem.

**Comment by Tyler-Ward** [comment]
Proposed fixing lists for teams

Cross-head wood screws
large and small (we already have these)

Hex head M3 bolts countersunk
* M3*8mm https://onecall.farnell.com/tr-fastenings/m3-8-kh10mc-s100/screw-socket-csk-m3x8/dp/1420610
* M3*12mm https://onecall.farnell.com/tr-fastenings/m3-12-kh10mc-z100/screw-socket-csk-bzp-m3x12/dp/1420651
* M3*20mm https://onecall.farnell.com/tr-fastenings/m3-20-kh10mc-s100/screw-socket-csk-m3x20/dp/1420613

Hex head M3 bolts cap head
* M3*8mm https://onecall.farnell.com/tr-fastenings/m3-8-so12cs-z100/screw-socket-cap-bzp-m3x8/dp/1419919
* M3*12mm https://onecall.farnell.com/tr-fastenings/m3-12-so12cs-s100/screw-socket-cap-m3x12-black/dp/1419604
* M3*20mm https://onecall.farnell.com/tr-fastenings/m320-so12cs-s100/screw-socket-cap-m3x20-black/dp/1419606

M3 other hardware
* M3 threaded rod https://uk.rs-online.com/web/p/threaded-rod/0530292/
* M3 nuts https://uk.rs-online.com/web/p/hex-nuts/0560293/
* M3 washers https://uk.rs-online.com/web/p/plain-washers/0560338/

**Comment by Tyler-Ward** [comment]
Have added the parts to the order list 200 of each of the screws above
