### ISSUE TITLE
[SP2019]Wipe/dispose of personal data

### ISSUE THREAD

**Issue by Tyler-Ward** [sourcebots/tasks#162]

**Comment by trickeydan** [comment]
Assuming that this was the USB sticks, it occurred

**Comment by kierdavis** [comment]
Surely this would include data about volunteers (e.g. emails, attendance, schedules, dietary preferences) too? Perhaps also the conference accounts' `H:` drives, but that might be isolutions' job.

**Comment by trickeydan** [comment]
I have deleted as much as we can for now. We need to keep contact details for remuneration

**Comment by trickeydan** [comment]
This is now done.

I have kept information for volunteers that agreed to be contacted about SP2020. All other information that I could find has been deleted.
