### ISSUE TITLE
[SP2019]Book Zepler lvl 2 for the prep weekend

### ISSUE THREAD

**Issue by Dasepho** [sourcebots/tasks#170]
Email Dave Oakley for booking Zepler level 2

**Comment by joe9599** [comment]
This is for the prep weekend (I believe)

**Comment by Adimote** [comment]
I've sent the email to Dave, Jenny has offered to prod him if he doesn't reply by Wednesday

**Comment by Adimote** [comment]
Looks like a planon ticket has been sent to request access to the room. @JennyLouise submitted the ticket

**Comment by Adimote** [comment]
Jenny will chase up Dave Oakley (and therefore the ticket) tomorrow

**Comment by JennyLouise** [comment]
It's been chased up, Dave says he's approved it, but the plan on ticket still just says "reported", so I'm not certain it's gone through. I guess we'll find out tomorrow morning. I'll be there bright and early to try out my card

**Comment by trickeydan** [comment]
Not much more we can do now. I'm closing this and we'll see how it goes tomorrow.

Thanks jenny :)

**Comment by kierdavis** [comment]
Ultimately we just used Tyler's card access when needed.
