### ISSUE TITLE
[SP2019]Consolidate Student Documentation

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#171]
We have rewritten the API docs for this year and also added the servo board to the kit.

Currently the docs are a little bit scattered between docs.sourcebots.org and sbot.readthedocs.io

We need to consolidate this. In particular, we need to remove the old API docs and preferably make the locations of things more known.

The current suggestion:

- Host sbot.readthedocs.io on kit.sourcebots.org
- Move the tutorials to labs.sourcebots.org
- docs.sourcebots.org to become legacy, but with a link between the two.

This task requires someone with DNS access.

**Comment by RealOrangeOne** [comment]
> We need to sort this all out

Can we get _a lot more_ context on what exactly is meant by this ticket.

**Comment by trickeydan** [comment]
> > We need to sort this all out
> 
> Can we get _a lot more_ context on what exactly is meant by this ticket.

Done, I didn't put much as I was just getting it down to not forget it.

**Comment by kierdavis** [comment]
I dislike the idea of having the docs split across multiple websites. can we not set up whatever is currently building docs.sourcebots.org to pull in sbot as a dependency and integrate its docs into the rest of the site?

**Comment by RealOrangeOne** [comment]
It's not quite that simple to integrate these things. Generally we just want a separation of things. The general intention is to take the docs we have currently, extract anything kit-related, and leave everything else as-is. 

We'd keep a link on the sidebar, it'd just be a link to somewhere else.

**Comment by trickeydan** [comment]
I personally think it'll be much easier to manage if it's all in one place.

**Comment by RealOrangeOne** [comment]
I don't know if we could use intersphinx to result in a final build which is just 1 site, but assuming we can't move the API docs out the `sbot` repo (maybe we can?), then I don't think we can or should merge them. It's odd to look for changing the docs about the entire event in the API repo

**Comment by trickeydan** [comment]
> I don't know if we could use intersphinx to result in a final build which is just 1 site, but assuming we can't move the API docs out the `sbot` repo (maybe we can?), then I don't think we can or should merge them. It's odd to look for changing the docs about the entire event in the API repo

We can move them out of sbot, but we will lose the autogenerated API references.

**Comment by RealOrangeOne** [comment]
> we will lose the autogenerated API references

Definitely don't want that!

In which case I suggest we go with the plan of simply redirecting a link on the sidebar to the `sbot` docs.

> This task requires someone with DNS access.

@Adimote is currently the person with DNS access for `sourcebots.co.uk`. As i'm likely the one owning this task, I'm happy to work out the changes we need to make, assuming I can get the `CNAME` record details off @trickeydan for the `sbot` RTD site.

**Comment by trickeydan** [comment]
The `CNAME` simply needs to be set as `readthedocs.io`.

I have added `kit.sourcebots.co.uk` to the config for now, but am happy to update if this is not the URL we want.

**Comment by RealOrangeOne** [comment]
Sounds like the perfect URL to me! @Adimote can you add the above records whenever. I'll deal with removing the docs content probably over the weekend.

**Comment by Adimote** [comment]
Done,

I added:

CNAME | docs | readthedocs.io

 should propagate soon!

**Comment by Adimote** [comment]
Oops I mean:

```CNAME | kit | readthedocs.io```

**Comment by RealOrangeOne** [comment]
![image](https://user-images.githubusercontent.com/6527489/62720658-5c22db80-ba02-11e9-9715-9858f1e64e1a.png)

Can confirm :+1:

**Comment by PeterJCLaw** [comment]
> * Move the tutorials to labs.sourcebots.org

Where are they currently?

**Comment by trickeydan** [comment]
> > * Move the tutorials to labs.sourcebots.org
> 
> Where are they currently?

With the old kit docs on docs.sourcebots.org

**Comment by kierdavis** [comment]
Based on the time constraints (we need to have this ready for smallpeice, and we still have changes to make) I recommend we put everything into the sbot (so we're not worrying about getting multiple sites to work together) and worry about whether things would be better located elsewhere after smallpeice.

**Comment by RealOrangeOne** [comment]
That's actually incredibly time consuming, vs simply removing what we have in the docs already, and adding a link to the new docs in the sidebar. 

In fact, i've already done it: https://github.com/sourcebots/docs/pull/151

**Comment by RealOrangeOne** [comment]
> We're overriding you... We're putting everything into `sbot`, because keeping it separate is stupid

It is therefore out of my hands.

**Comment by trickeydan** [comment]
> > We're overriding you... We're putting everything into `sbot`, because keeping it separate is stupid
> 
> It is therefore out of my hands.

I'm not sure if this is the best way to approach a dispute as it looks like there is one here. Given we have time tomorrow morning, I suggest that this is discussed then.

**Comment by trickeydan** [comment]
I don't want to be involved in this anymore.

**Comment by trickeydan** [comment]
This has caused a *major* issue as we announced the **old** documentation to them.

**Comment by PeterJCLaw** [comment]
Either this happened or it didn't.

**Comment by trickeydan** [comment]
This did happen, albeit very rushed and late.
