### ISSUE TITLE
[SP2019]Update Kit Build Tutorial

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#172]
- s/servo assembly/arduino/g
- add servo board
-Add photos

**Comment by kierdavis** [comment]
I don't mind doing this if I've got time, but I don't know where I should put it (relevant: #171).

**Comment by trickeydan** [comment]
Thanks Kier :) I'm happy to work on it too, I'd really like to get some photos added as the current tutorial is all text!
