### ISSUE TITLE
[SP2019]Organise a retrospective

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/tasks#174]
We are collecting a list of things to talk about here: https://hackmd.io/@sro/retro

**Comment by joe9599** [comment]
The retro will be happening today at 7pm

**Comment by kierdavis** [comment]
The points in the retro doc have been discussed and categorised. I think it would be good to draw up a more permanent document that we can refer to throughout the planning cycle for Smallpeice 2020. If people agree this is a good idea, I can have a go at doing this.
