### ISSUE TITLE
[SP2019]Brief volunteers about the labs

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/tasks#175]
We should make sure our volunteers have at least a rough idea what tasks the participants will be doing in advance of the mechanical, electronics and programming labs, so that they can guide the participants through the labs effectively.

This could be part of or immediately follow #128.

**Comment by trickeydan** [comment]
It should be part of #128, all volunteers need to know.

**Comment by sedders123** [comment]
Think the document @PeterJCLaw created here https://github.com/sourcebots/tasks/issues/103#issuecomment-517936728 is relevant. Not to be gone over in the briefing but volunteers should be sign posted to it and strongly encouraged to read it

**Comment by PeterJCLaw** [comment]
Labs have all happened.
