### ISSUE TITLE
[SP2019]Pay Delta-V

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/tasks#176]
We have requested to hire radios from Delta-V, but apparently the invoice hasn't been paid yet. It needs to be sorted ASAP or we won't have radios.

**Comment by trickeydan** [comment]
It seems that this won't happen in time for us to get them for Monday

**Comment by kierdavis** [comment]
Delta-V has been paid so we should be getting radios.

**Comment by tshoang** [comment]
I paid using my card. I will sort out with finance later.

**Comment by Adimote** [comment]
Woah Son, that was way beyond the call of duty, Thanks so much!
