### ISSUE TITLE
[SP2019]Check quantity of wire

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#18]

**Comment by jcwilliamson** [comment]
1x  30.5m Black 14 AWG (unopened)
1x 30.5m Red 16 AWG (unopened)
1x 100ft Blue 22 AWG (unopened)
1x 100ft Black 18 AWG (unopened)
1x 100ft Red 14 AWG (unopened)
1x 0.5kg enamelled wire 0.5mm (unopened)
1x 30.5m Blue 15AWG (mostly complete)
1x 100m Blue hookup wire (mostly complete)

**Comment by trickeydan** [comment]
This was checked.
