### ISSUE TITLE
[SP2019]Pay Mechanical Workshop

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#180]
The mechanical workshop were not paid for the motor mounts.

**Comment by JennyLouise** [comment]
Is this coming out of the SRO society budget, or does it need to be forwarded to ECS?

**Comment by jcwilliamson** [comment]
I believe this is being paid for by Son.

**Comment by trickeydan** [comment]
It needs a budget code so ECS will need to pay it.

**Comment by kierdavis** [comment]
Any idea if this has happened yet?

**Comment by trickeydan** [comment]
Given the lack of chasing, I think we can safely assume that this was sorted. Either way, it'll come out of the SP2020 budget
