### ISSUE TITLE
[SP2019]Finish assembling pi power hats

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/tasks#183]
We got the wrong component for D1, so all the Pi power hats are being assembled without this component on. We should choose a component that actually works, buy it and solder it onto all the boards.

Also, we only ordered 19 headers. We need to order more, and finish soldering them onto the boards.

**Comment by trickeydan** [comment]
We should consider if we are making a second hw revision before continuing.

**Comment by trickeydan** [comment]
There is going to be a second revision of this board.

**Comment by trickeydan** [comment]
Closed in favour of new revision of power hat.
