### ISSUE TITLE
[SP2019]Document the pi power board test procedure

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/tasks#184]
This is what I followed as part of #10:

* Visually inspect board.
* Plug in camcon connected to a PSU set to 5V.
* Check power LED is green.
* Check voltage on both output pins is 5V.
* Slowly reduce PSU voltage and check output cuts out at ~3.5V
* Slowly increase PSU voltage and check output cuts out at ~7V
* Return PSU voltage to 5V.
* Invert the polarity of the input connector.
* Check power LED is red.
* Check voltage on output is zero.
* Test each of the four GPIO LEDs by applying 5V to the corresponding pins.

We should put this into the docs, somewhere.

**Comment by trickeydan** [comment]
This should be placed into https://github.com/s-r-o/kb/

**Comment by trickeydan** [comment]
Is this much different to the SR procedure? I think it would be best to share docs with them as much as we can

**Comment by trickeydan** [comment]
We should write some proper documentation for these.

**Comment by kierdavis** [comment]
Migrated to roboticsoutreach/kb#31.
