### ISSUE TITLE
[SP2019]Organise Mentoring

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#186]
Student teams should be assigned a mentor who is familiar with their robot design.

This should be mentioned in #144.

1:1 ratio would be ideal but 1:2 would also work well.

**Comment by kierdavis** [comment]
It should be made clear (in a non-scary way) that this is a commitment for the week - mentors shouldn't be wandering off to the Cube halfway through the week. If they wish to switch roles they should let us know so a replacement mentor can be assigned.

Equally, it doesn't mean mentors have to be glued to their teams. I'd suggest aiming to check in with each of their teams and have a brief discussion about their progress and challenges a couple times an hour.

**Comment by Adimote** [comment]
I've assigned 8 people to always be around with the students in the schedule, so we can have teams per mentor

**Comment by trickeydan** [comment]
@Adimote can I hand this over to you as you've done it?

**Comment by andybusse** [comment]
We'll cover this at the volunteer brief (#128 )

**Comment by trickeydan** [comment]
This was done on Monday.
