### ISSUE TITLE
Chase up missing orders

### ISSUE THREAD

**Issue by sedders123** [sourcebots/tasks#188]
We are missing:
 - [ ] 3 x 35L Rubs
 - [x] Cardboard
 - [x] Power Tools
 - [x] **Prizes** - 1x Pi Kit
 - [x] **Prizes** - Prize mugs

These were ordered via Son

**Comment by tshoang** [comment]
Unfortunately, the Power Tools still "Waiting For Goods to arrive from Supplier". I have informed Dan on Friday about the Power Tools and sent an email to Shaun and Lee about them.

2019-07-30  11:09  187807 Order Status: Waiting For Goods to arrive from Supplier  Supplier: SGS Engineering
--
60805418 | 1.0000 | R18PD3-0 | RYOBI R18PD3-0 18V ONE+ HAMMER DRILL | 519191101 | tsh2n14 | 52.4760
60805418 | 1.0000 | RC18120-225 | RYOBI RC18120-225 ONE+ 18V LITHIUM+ 2X 2.5AH BATTERIES AND CHARGER

**Comment by tshoang** [comment]
Can you please remind me about other order (from which Order/Shop)? Thank you very much.

**Comment by Tyler-Ward** [comment]
Updates:
* Cardboard has been canceled
* Rubs were delivered and lost within the uni
* power tools are beng chased
* pi kit should be here today
* mugs still need collecting form joyce @JennyLouise are you planning on doing this?

**Comment by tshoang** [comment]
- I asked ECS Buyer (Shaun) to reorder 2 x 35L boxes (as it was said delivered).
- Shaun believed that the Pi is on its way (but as today, it is still no where to be seen). I asked Shaun again at the end of the day.
- Shaun will chase the order for Power Tool at the University level.
- The cardboard order has been cancelled (it was actually dispatched, however, we haven't received it in time)
(Just saw Tyler's post now but this is the update to that update).

**Comment by JennyLouise** [comment]
I've emailed Joyce, will email again, and will go by her office later today/tomorrow if I don't hear back.

**Comment by JennyLouise** [comment]
@tshoang, is there any update on this?

**Comment by trickeydan** [comment]
We're still waiting on these, so will move this to the Smallpeice 2020 Milestone.

**Comment by JennyLouise** [comment]
@tshoang, have you heard anything new about this?

**Comment by tshoang** [comment]
Dear Jenny,
 Just got a confirmation from ECS Store that the power tools never arrived. :-(
 Best regards,
Son

**Comment by trickeydan** [comment]
> Just got a confirmation from ECS Store that the power tools never arrived. :-(

That's a shame. What action are we taking?

**Comment by tshoang** [comment]
Surprised! The power tools arrived today. Not so sure where they were last year, but now it is in my office.

**Comment by trickeydan** [comment]
I've picked up the power tools, there were:

- 1 x Hammer Drill | Ryobi R18PD3
- 2 x Ryobi RB18L25 Batteries
- 1 x Ryobi RC18120 Fast Charger

Interestingly, the box for the hammer drill had been opened. It contained an instruction manual for a Ryobi BCL14183H Charger, which we have previous received in a different order.

**Comment by trickeydan** [comment]
It would be useful if the 3 x 35L RUBs could be found, as we are short on RUBs currently. However, I'm pretty sure that we've ordered them multiple times already and they always go missing for some reason. :(

**Comment by tshoang** [comment]
> I've picked up the power tools, there were:
> 
> * 1 x Hammer Drill | Ryobi R18PD3
> * 2 x Ryobi RB18L25 Batteries
> * 1 x Ryobi RC18120 Fast Charger
> 
> Interestingly, the box for the hammer drill had been opened. It contained an instruction manual for a Ryobi BCL14183H Charger, which we have previous received in a different order.

Do you mean that they misplaced these tools since the last year and suddenly realised that it is there all the time? In any case, I don't want to know.

**Comment by tshoang** [comment]
> It would be useful if the 3 x 35L RUBs could be found, as we are short on RUBs currently. However, I'm pretty sure that we've ordered them multiple times already and they always go missing for some reason. :(

We did order the boxes twice, none of them arrive (or they arrived, but Shaun did not know where they are). I am not so sure if we should order again through Shaun. If it is possible, I would rather get them myself and claim it back. However, I am not so sure I am allowed to do this.
