### ISSUE TITLE
[SP2019]Acquire promotional material

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#19]
- [x] Bags
- [x] prospectuses
- [x] promotional material
- [x] USB sticks
- [x] Mugs

**Comment by trickeydan** [comment]
This one will probably require an email to Reena / Joyce.

**Comment by trickeydan** [comment]
I poked Joyce about this the other day, but we should email them both to do it properly

**Comment by JennyLouise** [comment]
I'll send an email to both of them, and will ask to pick them up on the Friday/Saturday, the 9th/10th of August. Requesting 100 each of the items listed, and anything else they think would be good to add.

**Comment by JennyLouise** [comment]
We have 87 bags leftover from last year. Reena has said she can give us prospectuses, and Joyce has said she's all out of USB sticks but does have lots of sticky note pads and might get some pens made.

**Comment by JennyLouise** [comment]
Have added mugs to the list of items we need, Joyce has said she thinks she has 20 mugs for us to use as prizes but I'll get her to confirm actual numbers soon

**Comment by JennyLouise** [comment]
I'm meeting Joyce tomorrow afternoon (the 16th of July) to talk about all this stuff

**Comment by JennyLouise** [comment]
Met with Joyce and Marketing.
We have 

 - 30 USBs and 82 charging bands in a bag under my desk at Boldrewood that I can bring to the cupboard monday afternoon

 - 25 mugs in a box in Joyce's office, @Tyler-Ward can I borrow the cupboard key and use a trolley or something similar to shift them over to our cupboard on level 4? Joyce isn't around on the 9th for us to pick them up and take them straight to our prep room.

 - Once a room for competition prep is booked we can email visit.feps@soton.ac.uk to have 100 prospectuses delivered to the room for friday afternoon. At the moment we just have the ECS Undergraduate Courses booklet, but if we want any other material just let me know and I can ask them

 - The 87 bags leftover from last year already in the SRO cupboard, ready to put all this stuff in!

Let me know if we need anything else

**Comment by Tyler-Ward** [comment]
If you are around on monday i can give you the key then

**Comment by JennyLouise** [comment]
Marketing have said they'll drop prospectuses off at lvl 4 mountbatten this afternoon

**Comment by kierdavis** [comment]
These have arrived. Looks like that's everything needed for this ticket, so I'll close.

![IMG_20190809_133556356](https://user-images.githubusercontent.com/845652/62779908-584b9380-baac-11e9-84c7-c01c15518293.jpg)

**Comment by Tyler-Ward** [comment]
We still need to collect mugs from Joyce

**Comment by JennyLouise** [comment]
Mugs have been collected, they are in a cardboard box in the left hand cupboard in level4 mountbatten
