### ISSUE TITLE
[SP2019]Put software on laptops

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#190]
We've got 16 laptops from isolutions. We need to boot them up, check we can log in, and install pycharm.

_Originally posted by @kierdavis in https://github.com/sourcebots/tasks/issues/86#issuecomment-520488219_

**Comment by kierdavis** [comment]
They are domain-build, so we can't install pycharm on them.

**Comment by kierdavis** [comment]
A workaround is to build some live USBs.

**Comment by PeterJCLaw** [comment]
We booted one up:
- it requires a network connection (cable or WiFi) in order to be logged into; it asks for credentials for Eduroam
- when logging in with an `@soton.ac.uk` account, it _doesn't_ automatically connect to  Eduroam with the login credentials

Unfortunately we didn't try installing anything.

**Comment by PeterJCLaw** [comment]
We've confirmed that there's a place on the machines which we can put things so that they persist being logged out and between different users.

Plan is to use that, combined with a PowerShell script which uses chocolatey to install the programs we want (many in a portable mode).

**Comment by PeterJCLaw** [comment]
Turns out, we might actually have admin on the laptops. This is frustrating to find out now, but makes this much easier.

**Comment by nmalky** [comment]
(it appears that the "admin" we get doesn't do what we want).
@PeterJCLaw @trickeydan will you be able to configure things? I won't be around until 2pm or so.
- install python3.7 separately, from the website 
- then, pycharm should work (can install manually if need be)

**Comment by PeterJCLaw** [comment]
Sorry, only just seen this. I'm currently busy in the Cube, so I doubt I'll get to look at this any time soon.

**Comment by PeterJCLaw** [comment]
This is apparently not happening. The competitors will need to do this themselves under guidance from us.
