### ISSUE TITLE
[SP2019]Push Board FW Changes Upstream

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#193]
We have made some minor modifications to the board firmwares. 

We should push them upstream and then archive the repos.

**Comment by kierdavis** [comment]
Power board: already been upstreamed, possibly by accident.

Motor board: I've opened https://github.com/sourcebots/motor-v4-fw/issues/1 to track this.

Servo board: we don't have a sourcebots fork of the servo board firmware (yet).

**Comment by trickeydan** [comment]
This is being tracked in individual repos
