### ISSUE TITLE
[SP2020]Add SRO-AAM-ODQ to inventory

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/tasks#199]
We have a raspberry Pi labelled SRO-AAM-ODQ, but this asset code doesn't exist in the inventory. We should add it, or assign it a new asset code. This should be in the same RUB as the rest of the raspberry pis.

**Comment by trickeydan** [comment]
We should locate this on Sunday and add it to the inventory.

**Comment by trickeydan** [comment]
Done
