### ISSUE TITLE
[SP2019]Find owner(s) of lost coat and umbrella

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/tasks#202]
A coat and an umbrella were left behind in level 2 labs at the end of the week, probably from a competitor or Smallpeice supervisor. We should contact Smallpeice and see if anyone claims it.

Note that #194 also relates to returning lost property; these could be done at the same time.

![IMG_20190817_200543881](https://user-images.githubusercontent.com/845652/63290122-ad5f8480-c2b8-11e9-9708-640aa60745bd.jpg)
![IMG_20190817_200552127](https://user-images.githubusercontent.com/845652/63290123-ad5f8480-c2b8-11e9-935a-3fbdeab6320d.jpg)

**Comment by trickeydan** [comment]
This is unlikely to happen if it hasn't happened already

**Comment by trickeydan** [comment]
These were taken to ECS reception as lost property
