### ISSUE TITLE
[SP2019]Plan Cube refreshments

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#21]

**Comment by trickeydan** [comment]
Is this even our responsibility?

Son seems to want to do this I think

**Comment by Adimote** [comment]
Arrange with SUSU, probably part of #85

**Comment by trickeydan** [comment]
George at SUSU has prodded SUSU catering

**Comment by Adimote** [comment]
Any update on this? If not we should send some people to sainsburys

**Comment by Adimote** [comment]
SUSU is waiting on a purchase order for this

**Comment by Adimote** [comment]
(So it should be sorted, as it's at the same state as SUSU tech which needs to happen)

**Comment by trickeydan** [comment]
This has been arranged and is now in the hands of finance and SUSU.
