### ISSUE TITLE
Order Arena Props

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#224]
Blocked on knowing the game #219

**Comment by trickeydan** [comment]
102mm cardboard boxes were ordered in Order 2

**Comment by RealOrangeOne** [comment]
@Dasepho could you check for these in the cupboard (or wherever else they may be)? If we have them, then they'd make great tokens and we can just shrink down the ones in the simulator.

**Comment by Dasepho** [comment]
Will do, I have a vague recollection of about 5 or 6 leftover ones in the cupboard, not sure about more. In any case will update after I've got access to the cupboard
