### ISSUE TITLE
[SP2021]Hire laptops

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#228]
We need to hire one laptop per team (so 16), from at least Wednesday -> Friday.

Last year, we hired these through iSolutions

**Comment by JennyLouise** [comment]
Do you have a recommended email address to get in touch with them, or do we need to raise a ticket?

Could we ask Son to handle this? He'll probably have better connections with isolutions than we do.

**Comment by trickeydan** [comment]
> Do you have a recommended email address to get in touch with them, or do we need to raise a ticket?

I believe we have to raise a serviceline ticket.

> Could we ask Son to handle this? He'll probably have better connections with isolutions than we do.

This is what we should do, this ticket mostly exists so that we action that and so that we can track it.

**Comment by WillB97** [comment]
These are not needed for the 2021 event
