### ISSUE TITLE
Plan the schedule

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#232]
We need a schedule.

**Comment by RealOrangeOne** [comment]
The current canonical schedule is in Teams. It's fairly well planned, but keeping this open until it's fixed.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne is there a link to where we can see the schedule?

**Comment by PeterJCLaw** [comment]
Turns out: it's in Teams. Go to Chat then to Files (in the header on the left), then to Schedule.
