### ISSUE TITLE
[SP2021]Prepare "Student Packs"

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#233]
TASK: Print Rules
    TASK: Pack promotional items e.g pens
    TASK: Acquire bags
    TASK: Print maps of campus (mark key areas?)
    TASK: Acquire Prospectuses
    TASK: Pack the student packs

**Comment by trickeydan** [comment]
Dependent on #225

**Comment by RealOrangeOne** [comment]
N/A for a virtual event.
