### ISSUE TITLE
[SP2021]Update programming labs with a vision tutorial

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#237]
We need to finalise the programming labs

**Comment by trickeydan** [comment]
These labs needed improvement after last year, but I think that we're already thinly spread over existing tasks.

I propose that we update to add a tutorial for basic vision, and then deem the labs to be finalised.

@Dasepho @JennyLouise Any thoughts?

**Comment by Dasepho** [comment]
With a vision tutorial, I'd consider these shippable. Once that's done, we could mark some updates as `Nice to have`

**Comment by RealOrangeOne** [comment]
No vision this year.
