### ISSUE TITLE
[SP2021]Finalise electronics labs

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#238]
Once finalised, these need to be published and parts need to be ordered.

**Comment by trickeydan** [comment]
https://github.com/sourcebots/labs/pull/26

**Comment by trickeydan** [comment]
I've fixed the merge conflicts and bumped the date, I suspect that these are done as soon as @joe9599 has a chance to double check them.

**Comment by Dasepho** [comment]
Are we doing anything electronics labs wise this year (virtual comp)?

**Comment by RealOrangeOne** [comment]
No.
