### ISSUE TITLE
[SP2019]Check quantity of arena build materials

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#24]

**Comment by trickeydan** [comment]
Qualitative count : Not much

**Comment by Tyler-Ward** [comment]
Arena planks are 70mm wide

**Comment by drn05r** [comment]
[sr_wood_20190727.xlsx](https://github.com/sourcebots/tasks/files/3438452/sr_wood_20190727.xlsx)

Here is an excel spreadsheet of the wood in the cupboard.  All meaurements are in mm.  There are a few small pieces of timber, ply and fibreboard that was not measured.

**Comment by trickeydan** [comment]
This has been done. Thanks @drn05r :)

**Comment by Tyler-Ward** [comment]
now on google docs for editing https://docs.google.com/spreadsheets/d/1uDQTWzklu0lDSMTtkIVEPOFIhDJw13x80aKt6NLL_mA/edit#gid=0
