### ISSUE TITLE
[SP2021] Prepare simulator

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#240]
This lab teaches the subset of Python specific to our Robot API. It usually uses a simulator of some kind.

    TASK: Setup the Simulator for this years game
    TASK: Distribute simulator

**Comment by PeterJCLaw** [comment]
I suspect that this will be subsumed by #275 given that the simulator will be part of that?

**Comment by PeterJCLaw** [comment]
Since the first lab session has happened I'm calling this done.
