### ISSUE TITLE
Arrange for arena parts

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#243]
- Scaff / Truss
- Wood screws

Not really sure what gets ordered here

**Comment by trickeydan** [comment]
@WillB97 Do you think you'll be able to work out what parts you need? I'm completely in the dark on this one, am hardly ever at the cube whilst it's being built

**Comment by WillB97** [comment]
Last I saw we had a RUB with several thousand screws so this will mainly be for
-  a 4x4ft stage deck
- truss for the arena perimeter
