### ISSUE TITLE
[SP2021] Plan Match Schedule

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#246]
We need a match schedule.

Depends on https://github.com/sourcebots/tasks/issues/232 since we need to fit the matches into the available time.

**Comment by PeterJCLaw** [comment]
@tpoomlmly do we have the timings for Friday morning? Essentially the first thing we need here is the time window that the matches can occupy and we'll work out the schedule based on that.
We'll need to allow for things like the prize-giving too, so this depends on #232.

**Comment by tpoomlmly** [comment]
09:40-10:40 - competition time
10:40-11:40 - tinker time
11:40-12:40 - competition time

Then the closing address at 12:40

**Comment by PeterJCLaw** [comment]
Does the closing address include the prize giving? (When I asked @RealOrangeOne previously he seemed to think the prize giving needed to happen before 12:40)
Essentially: if the final match finishes at 12:40, is that ok? (ignoring turnaround time for preparing the prize giving)

**Comment by RealOrangeOne** [comment]
The intention is to do the prize giving during the stream, then switch to Meet for closings and speeches. All that needs to end by 13:00. 12:40 for the final match end probably isn't ideal if we also need to transition mediums.

**Comment by PeterJCLaw** [comment]
The other question for planning the prize giving is how far in advance we'll have the deadline for the teams' code. That determines how far in advance we'll know who's won. I guess it also impacts whether tinker time makes sense.

**Comment by PeterJCLaw** [comment]
This has happened (see https://github.com/sourcebots/compstate-smallpeice2021/pull/3, https://github.com/sourcebots/compstate-smallpeice2021/pull/4, https://github.com/sourcebots/compstate-smallpeice2021/pull/5).
