### ISSUE TITLE
[SP2021] Setup SRComp

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#248]
We need SR-COMP or a suitable alternative (such as a whiteboard)

**Comment by PeterJCLaw** [comment]
Assuming that this means "SRComp", I'm happy to pick this up. Since this year is going to be lots of remote things, we probably do want to use something which supports being decentralised rather than just a whiteboard.

**Comment by PeterJCLaw** [comment]
https://github.com/sourcebots/compstate-smallpeice2021 now exists, so we have a place to store the match data. We'll want a compbox too, however that's easy enough to set up. 

@RealOrangeOne does Sourcebots have a Digial Ocean account or anything? If not I'm happy to just use my own - likely we don't need a big machine nor for very long.

**Comment by RealOrangeOne** [comment]
To my knowledge they don't have any hosting, but defer that to @tpoomlmly. Chances are just using your account is probably a lot faster and easier if you're ok with that.

**Comment by tpoomlmly** [comment]
There's no hosting at the moment (which is why the website's down right now). We used to use one of Dan T's droplets but that evapourated.

**Comment by sedders123** [comment]
Happy to chuck my account into the ring if useful

**Comment by PeterJCLaw** [comment]
> the website's down right now

Off topic, but https://sourcebots.co.uk/ looks up to me... is that not the website? (Is there a reason not to use GitHub pages directly?)

I'm assuming that I'll configure a https://github.com/PeterJCLaw/srcomp-puppet instance as `srcomp.sourcebots.org`/`srcomp.sourcebots.co.uk`, as I have in the past and run things from there.
Do shout if it needs to be a different domain though.

**Comment by RealOrangeOne** [comment]
Nope that should be fine. FYI @Adimote is the keeper of the `sourcebots.co.uk` DNS.

**Comment by PeterJCLaw** [comment]
The compbox is live, https://sourcebots.co.uk/comp is showing data from it. I'm calling this done.
