### ISSUE TITLE
[SP2021]Build the arena

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#249]
We need an area.

**Comment by WillB97** [comment]
I have a source of metric stage deck that is 110mm tall, is this of use?

**Comment by trickeydan** [comment]
> I have a source of metric stage deck that is 110mm tall, is this of use?

Possibly, imo you get free reign over how you want to build it. :) 

However, I did spend ages updating all of the diagrams and measurements to be 1.2m 

https://8-190781232-gh.circle-artifacts.com/0/rules.pdf for reference.

**Comment by PeterJCLaw** [comment]
There was indeed a (mini) arena.
