### ISSUE TITLE
[SP2019]Plan game

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#25]
@prophile

**Comment by Dasepho** [comment]
Meeting dedicated to this 2019-05-27 in usual SRO slot

**Comment by Dasepho** [comment]
Problem: next week is a bank holiday. We need to work out how / where we can hold this meeting

**Comment by trickeydan** [comment]
Worst case, we can go to Futureworlds. There are conferencing facilities there that we can use

**Comment by Dasepho** [comment]
Decision made, based on [Apple tree](https://drive.google.com/file/d/1Iv3tupVu0DaCbwnhn0LF3hBSwTYSz3jr/view)
I'll update it to reflect the discussed points

**Comment by Dasepho** [comment]
New version is [here](https://drive.google.com/open?id=1Iv3tupVu0DaCbwnhn0LF3hBSwTYSz3jr). Will be written up formally as rules for teams later. A few things like number of points for different cubes to be finalised later, but enough done to unblock issues I think

**Comment by Dasepho** [comment]
Replacing this issue with #81 now we know the general game idea
