### ISSUE TITLE
Order things

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#256]
We need to order things according to the order list.

This task exists so that we order things, but should not be tracked here until all non-specific ordering has been done.

**Comment by trickeydan** [comment]
Order 1 was ordered, and has arrived.

We are currently missing 19 x XT60 connectors from Mouser.

ECS Stores know that it is missing, and it is apparently on its way.

**Comment by trickeydan** [comment]
Order 2 has been sent to Son.

**Comment by tshoang** [comment]
The XT60 connectors have arrived and in my office.

**Comment by tshoang** [comment]
> Order 2 has been sent to Son.

Order 2 is now with ECS Buyer.

**Comment by tpoomlmly** [comment]
Order 2 was never ordered due to Covid, we'll need to resubmit

**Comment by RealOrangeOne** [comment]
Things were ordered.
