### ISSUE TITLE
[SP2021]Print Rules

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#257]
We will need to print the *final* copies of the rules.

Any outstanding issues on the rules repo will need to be considered.

**Comment by Dasepho** [comment]
Virtual, so no printing for competitors this year. We should maybe still have a printed 'canonical' copy for volunteers?
Either way, will leave this issue for the 'consider outstanding issues on rules repo'

**Comment by RealOrangeOne** [comment]
Given that we'll all going to have to be infront of computers, physical copies probably aren't necessary.
