### ISSUE TITLE
[SP2021]Ensure we have enough kit

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#260]
We need to ensure that we have a minimum of:

- 16 x Pi
- 16 x Power Board
- 16 x Motor Board
- 16 x Servo Board
- 16 x Arduino

This could be achieved through #5 or through a loan from SR.

**Comment by RealOrangeOne** [comment]
We're running a virtual competition, with a limited number of physical robots, so whilst we need kits, very few of them.

**Comment by PeterJCLaw** [comment]
There were physical robots, so we probably had enough kit.
