### ISSUE TITLE
[SP2021]Flash OS images to SD cards

### ISSUE THREAD

**Issue by tpoomlmly** [sourcebots/tasks#263]
The version of SourceOS on the SD cards currently is out of date and they need to be reflashed.

**Comment by trickeydan** [comment]
Blocked on having a final OS image.

**Comment by RealOrangeOne** [comment]
Virtual competition, so no physical kit to flash.

**Comment by sedders123** [comment]
We do have physical robots as part of one of the tutorials so we will still need to do this

**Comment by PeterJCLaw** [comment]
Physical robots happened.
