### ISSUE TITLE
Buy hacksaw blades

### ISSUE THREAD

**Issue by tpoomlmly** [sourcebots/tasks#266]
We've got some hacksaws, but they don't have any blades so we need to order some more.

**Comment by jefftheprogrammer** [comment]
What blade size do we need?

**Comment by trickeydan** [comment]
> What blade size do we need?

Not sure, the saws should be inspected to see if we can determine this

**Comment by WillB97** [comment]
I believe they're full size hacksaws so they'll be 12" blades. I'd recommend a 24-32tpi blade.

**Comment by WillB97** [comment]
Something like this would be fine: https://www.amazon.co.uk/gp/product/B07C75CPRG/

**Comment by tpoomlmly** [comment]
We have hacksaw blades now
