### ISSUE TITLE
Buy missing things for finishing power boards

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#267]
- 2 metres red 4.8mm double-walled heatshrink
- 2 metres black 4.8mm double-walled heatshrink
- Access to uninsulated ring terminal crimp tools
- Stickers for marking where things are (#29)

**Comment by jefftheprogrammer** [comment]
Added to 2021 late prep. The missing things will be added to smallpiece 2021 order 1.

**Comment by tpoomlmly** [comment]
Power boards finished woo
