### ISSUE TITLE
[SP2021]Plan SP2021 Game

### ISSUE THREAD

**Issue by tpoomlmly** [sourcebots/tasks#269]
This includes:

- [ ] Arena Design

- [ ] Arena Diagram

- [ ] Overview of game rules

**Comment by tpoomlmly** [comment]
We could use the unused game from last year; see https://github.com/sourcebots/smallpeice-rules/pull/10 and #220

**Comment by Dasepho** [comment]
Mostly planned: see Teams for design doc link (avoid leaking rules if possible)
TLDR: it's pushing tokens, themed around a dock yard

**Comment by RealOrangeOne** [comment]
This is now covered by #271.
