### ISSUE TITLE
[SP2021]Find a competition venue

### ISSUE THREAD

**Issue by tpoomlmly** [sourcebots/tasks#270]
We need to know if we're going to run the competition in the Cube as usual, or if we're going to use another venue like Building 100.

We need venues for:

- [ ] Competition
- [ ] Team pits
- [ ] Testing arena
- Maybe some others I haven't thought of yet

**Comment by trickeydan** [comment]
Worth looking at layouts from previous years, see #149

**Comment by Dasepho** [comment]
Virtual comp, so no team pits etc
Will have small physical arena in Zepler level 3 (with space for volunteers) as part of tutorials

**Comment by RealOrangeOne** [comment]
Competitors will be virtual, along with some volunteers. Most volunteers will be in L3 labs.
