### ISSUE TITLE
[SP2021] Finalise Rules

### ISSUE THREAD

**Issue by tpoomlmly** [sourcebots/tasks#271]
Take the game from #269 and write it into a formal rules document. We could use last year's unused rules, see #269 and #220

**Comment by PeterJCLaw** [comment]
Since the rules have been published (https://github.com/sourcebots/docs/pull/181), I'm calling this done. @prophile feel free to reopen

**Comment by PeterJCLaw** [comment]
https://github.com/sourcebots/smallpeice-rules/pull/17 still needs merging :(

**Comment by tpoomlmly** [comment]
Where are the beacons? the docs say that the rules say

**Comment by tpoomlmly** [comment]
The rules say it now, they're finalised
and https://github.com/sourcebots/smallpeice-rules/pull/17 has been merged
