### ISSUE TITLE
Complete smallpiece 2021 order 1 and send it to Son

### ISSUE THREAD

**Issue by jefftheprogrammer** [sourcebots/tasks#272]
2020 Order 2 (issue #256) is now merged with 2021 Order 1. Requested items from issue #267 have also been added to 2021 Order 1.

2 issues with 2020 Order 2:
- You cannot order 10 32gb SD cards anymore.
- They no longer sell packs of 10 boxes anymore. 

The prices from Order 2 would also need to be rechecked to ensure they are correct.

**Comment by tpoomlmly** [comment]
The SD cards turned out to have a limit of 5 per customer.
