### ISSUE TITLE
Organise livestream

### ISSUE THREAD

**Issue by RealOrangeOne** [sourcebots/tasks#273]
There will be a livestream for the finals (including prize giving, excluding closing ceremony).

We'll be using the Smallpeice YouTube channel, which will require coordinating with someone on their side to get the stream key.

**Comment by PeterJCLaw** [comment]
How much lead time do you expect to need to get the stream key?

**Comment by PeterJCLaw** [comment]
Once we have the url we should input it into https://github.com/sourcebots/competition-website/tree/hugo-sp2021 (see also https://github.com/sourcebots/tasks/issues/276)

**Comment by PeterJCLaw** [comment]
The url is live at https://sourcebots.co.uk/comp, so I think that part is done. Not sure what else is needed here.

**Comment by RealOrangeOne** [comment]
This (the organising) happened
