### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by RealOrangeOne** [sourcebots/tasks#274]
https://github.com/sourcebots/docs is the repository we're using for this.

- API reviewed and updated for correctness, completeness, and making it obvious which bits are physical/virtual only
- Kit reviewed, and anything unnecessary removed
- New python guide put in place of whirlwind tour
- Simulator documentation (See https://studentrobotics.org/docs/simulator/)

**Comment by PeterJCLaw** [comment]
The docs are as updated as they're going to be.
