### ISSUE TITLE
Update & deploy competition-website

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/tasks#276]
https://github.com/srobo/competition-website/ has a branch which has the SourceBots branding. Since we're remote this year, having it would be useful. However it likely needs updating and may need the porting of the two-team arena support.

**Comment by PeterJCLaw** [comment]
https://github.com/sourcebots/competition-website/tree/hugo-sp2021 now exists. No plan to merge it to master though.

@RealOrangeOne I'm assuming you know things about how https://sourcebots.co.uk/ is hosted -- is it GitHub pages or a VM somewhere? How can we facade it over to being the competition website?

**Comment by RealOrangeOne** [comment]
It's hosted with Netlify. We can either point DNS over, or route just a single path (eg `/comp`). The latter being marginally easier.

**Comment by PeterJCLaw** [comment]
How do you suggest we do the homepage takeover?

**Comment by RealOrangeOne** [comment]
That can be done with a redirect as well

Should be just a few lines of change https://docs.netlify.com/routing/redirects/rewrites-proxies/

**Comment by PeterJCLaw** [comment]
Does Sourcebots have a netlify account already? If so, how can we go about adding https://github.com/sourcebots/competition-website/tree/hugo-sp2021 to it? (I can't recall at all how we deployed it previously)

**Comment by PeterJCLaw** [comment]
https://sourcebots.co.uk/comp is live.

**Comment by PeterJCLaw** [comment]
Calling this done. We've directed the competitors to https://sourcebots.co.uk/comp, so we don't strictly need the homepage takeover.
