### ISSUE TITLE
Hold a society planning meeting

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#282]
- Marketing
- Online precence
- Bunfight
- Volunteer Retention
- Initial sessions for freshers
- Scope of society's activities for next year

We will need to use our resources in the university as much as possible to make sure we are successful this year.

@tpoomlmly Please send out a doodle poll to as many people as possible, we need this meeting within the next two weeks at most.

**Comment by jefftheprogrammer** [comment]
@trickeydan Thank you Dan for your summary of what should be discussed. Here is the doodle poll for the next meeting:https://doodle.com/poll/rhw5ryqex7rkmgct

In addition (although this is mostly relevant to tommy) we would need to discuss what needs to be done in the immediate future, eg:

- Holding an AGM #279 
- checking the post box #281 
- Transferring the bank account to me and Tommy. #278
