### ISSUE TITLE
Design and order case stickers

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#29]

**Comment by Dasepho** [comment]
I'm happy to do, do we have existing files to work from of are we doing new ones?

**Comment by trickeydan** [comment]
Worth noting that we are unlikely to get this done in time for the 15th.

We should probably action this much sooner, moving forward in timescale.

**Comment by jefftheprogrammer** [comment]
Needs to be something like that: https://www.lemark.co.uk/accessories/pal-case-label-starter-pack/

**Comment by tpoomlmly** [comment]
Power etc. boards are done now
