### ISSUE TITLE
[SP2019]Make a schedule & plan for moving things

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#30]

**Comment by Adimote** [comment]
I'm not sure I understand what this ticket means

**Comment by trickeydan** [comment]
@jcwilliamson Do you remember what this ticket was?

**Comment by jcwilliamson** [comment]
I think primarily it was about how we're going to get everything where it needs to be, when it needs to be there. Also an element of storage during competition possibly.

**Comment by WillB97** [comment]
Is this covered in #125?

**Comment by trickeydan** [comment]
I think it has a slighter wider scope but am unsure

**Comment by sedders123** [comment]
We now have a pile of stuff being moved by estates, a large number of items in L2 labs, and we will move the rest of the stuff as needed.
