### ISSUE TITLE
[SP2019]Plan battery chargers and count lipo bags

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#31]

**Comment by jcwilliamson** [comment]
I believe we had approximately 3 lipo bags where the velcro wasn't falling off. @Tyler-Ward is ordering more of these.

**Comment by trickeydan** [comment]
Lipo bags have been counted. This data is in the inventory

**Comment by Tyler-Ward** [comment]
This is done and have arrived
