### ISSUE TITLE
[SP2019]Create cost breakdown of kit manufacture and send to Joyce

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#32]
@kierdavis can you handle this?
This will also need to be checked against the Smallpeice budget to figure out what the deficit is.

**Comment by kierdavis** [comment]
Yeah I'll get this sorted ASAP.

**Comment by trickeydan** [comment]
@kierdavis Any estimated times on this task?

I would do it, but I have no idea how

**Comment by kierdavis** [comment]
I'm very sorry - given the kit agreement with SR, I thought this wasn't that urgent. My plan is to start sorting this out on Monday but if its urgent I can try and make some progress on it tonight/tomorrow morning.

The first step is to [pick up where we left off in March](https://github.com/sourcebots/kit-manufacture-2019/issues) and get a quote finalised so we know how much it will cost to outsource manufacture, which I'm expecting to take a nontrivial amount of time. After that its just a matter of crunching some numbers and contacting Joyce - is there a relevant email thread you could CC me into?

**Comment by trickeydan** [comment]
It's urgent as in we need to do it before Joyce's budget expires in a couple of weeks.

There is no email thread yet, as I spoke to her in person. I'll set up one when I get chance.

**Comment by kierdavis** [comment]
This spreadsheet lists the price breakdown for the quotes I've been able to get so far: https://docs.google.com/spreadsheets/d/1zE_gw8idO3K-fdvhHla8w_M4fcu3P_LFyxQ6oa0C2X4/edit

I'm also in contact with Garner Osborne but the quote is currently held up due to a component going out of stock. (see https://github.com/sourcebots/kit-manufacture-2019/issues/13).

Regardless, is this enough information to give to Joyce?

**Comment by jcwilliamson** [comment]
Would there be any possibility of finding a compatible replacement for that component? That might allow us to speed up the process.

**Comment by kierdavis** [comment]
I've had a look and found one replacement, but its only available from one supplier (that I've never heard of). Gonna see if Garner Osborne accept it or not.

**Comment by kierdavis** [comment]
This happened, culminating in an email to Son and Joyce summarising [this information](https://docs.google.com/spreadsheets/d/1zE_gw8idO3K-fdvhHla8w_M4fcu3P_LFyxQ6oa0C2X4/edit#gid=119533467). Further steps will be tracked in #5.
