### ISSUE TITLE
[SP2019]Count SR RUBs in broom cupboard

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#37]

**Comment by jcwilliamson** [comment]
@mildlyincompetent @trickeydan am I correct in thinking that we did this Wednesday? Should this be closed now?

**Comment by trickeydan** [comment]
@jcwilliamson unfortunately not

This ticket refers to Rubs with SRO kit in also

**Comment by jcwilliamson** [comment]
It might make sense to link this with some of the other cupboard based tasks, because you can parallelise most  of them quite nicely. It would be great if we could get a decent chunk of them done in one go.

**Comment by trickeydan** [comment]
Done
