### ISSUE TITLE
[SP2019]Purchase arena props

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#38]
blocked on ~#25~

**Comment by trickeydan** [comment]
![aww-board](https://user-images.githubusercontent.com/7862359/61995692-95169400-b083-11e9-905a-fba22da2b533.png)

Things needed:

- Copper Tape
- Stage Decking (#141 )
- Tokens (Boxes and card purchased)
- Coloured Tape (Purchased)
- Hardboard to face stage decking
- Stickers to mark the random positions. (4 colours, two per position)

**Comment by trickeydan** [comment]
See #152
