### ISSUE TITLE
[SP2019]Ordering RUBs for cupboard

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#4]
This is blocked on sorting the cupboard

**Comment by WillB97** [comment]
Has this now been completed?

**Comment by kierdavis** [comment]
Not sure - we have ordered and received some RUBs, but we could still do with more since we ended up with quite a few "misc" crates after Smallpeice.

**Comment by trickeydan** [comment]
The scope of this for SourceBots has been sorted.
