### ISSUE TITLE
[SP2019]Design and order t-shirts

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#40]

**Comment by Dasepho** [comment]
I'm happy to do this after this week if I'm given some guidance on what sort of thing we want.
Do we have a company lined up to order from?

**Comment by trickeydan** [comment]
> I'm happy to do this after this week if I'm given some guidance on what sort of thing we want.
> Do we have a company lined up to order from?

I can help with design. It'll be similar to last year.

Yes, we have a standard supplier for t-shirts.

**Comment by Adimote** [comment]
@JennyLouise has made designs and put them in the drive, (Thanks Jenny!) 
They just need ordering!

**Comment by trickeydan** [comment]
I'm forwarding the order details to ECS.

**Comment by trickeydan** [comment]
Forwarded to ECS

S | 4
-- | --
M | 13
L | 5
XL | 0
XXL | 1

Plus 1S, 2M, and 1L spares if we have money
