### ISSUE TITLE
[SP2020]Investigate single LiPo Battery bags

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#41]

**Comment by kierdavis** [comment]
Presumably this is referring to something like this:

![lithium polymer battery and protective bag for said battery](https://www.flyingtech.co.uk/sites/default/files/Product_images/Racing-Drone-LiPo-Bag.jpg)

In which case, I'm in favour - these would be more space efficient than our current bags. Although our current bags can fit 5 or 6 batteries I'm not a huge fan of the idea of storing more than one battery in the same bag for safety reasons.

**Comment by jcwilliamson** [comment]
I think this is what we want. I agree with Kier on this one, having all those batteries in the same bag is perfectly fine while they're okay, but increases the odds that it'll go really wrong when something finally does happen. Plus these would probably stack nicely in a RUB.

**Comment by trickeydan** [comment]
We do not have a budget for these this year unfortunately.

**Comment by trickeydan** [comment]
That's not saying we're dismissing it entirely, I still think these are a good idea.
