### ISSUE TITLE
Send out volunteer sign up form

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#42]
@RealOrangeOne "Sort out the damn email address" - Dan Trickey

**Comment by trickeydan** [comment]
I'm going to send this out tomorrow _regardless_ of whether the issue with the form is resolved, we need to start recruiting.

**Comment by RealOrangeOne** [comment]
> "Sort out the damn email address" - Dan Trickey

I'm not happy with this attitude towards me. I've had many conversations with Dan which have culminated with "Yes, I can create the accounts you need, just tell me what you want", and apparently fallen on deaf ears, then to be repeated a couple of weeks later when Dan chases me up, for _something_. 

Once someone tells me what's needed, I can create the accounts. 

If this ticket is simply about sorting out a correct mailbox for contact, then we should name the ticket as such.

**Comment by RealOrangeOne** [comment]
A valid email address has been added to the form.
