### ISSUE TITLE
[SP2019]Replace pin headers

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#43]
Boards were stepped on by me, pin headers are bent, but otherwise boards appear ok. Needs replacement.

**Comment by Dasepho** [comment]
Do we have replacements to hand; is this a soldering job or a purchasing job?

**Comment by jcwilliamson** [comment]
They're just 2.54mm pitch headers, pretty sure we own a load of them.

**Comment by Dasepho** [comment]
Ok, great. Someone with B16 access can do this pretty easily then. After this week of exams, @joe9599 and I might be able to do it. How many boards are there to do?

**Comment by jcwilliamson** [comment]
I think 2. I'm also happy to do them. I just forgot to get them from the
cupboard last night.

**Comment by joe9599** [comment]
I am good to do stuff from Friday afternoon if you need hands for this

**Comment by Dasepho** [comment]
Removed the bent pin headers. Didn't put new ones on.

**Comment by joe9599** [comment]
The headers have been replaced
