### ISSUE TITLE
[SP2019]Purchase Isopropyl Alcohol

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#45]

**Comment by joe9599** [comment]
How much IPA do we need, heres 500ml from RS, do we need it in an aerosol can or in a form which we can easily pour, e.g. for filling the blue bottles found around labs
https://uk.rs-online.com/web/p/precision-cleaners-degreasers/0567890/

**Comment by trickeydan** [comment]
We need it for cleaning glue residue off things mostly, and it's useful to have some around anyway.

I think a pouring form is most useful, but am open to an aerosol too.

**Comment by joe9599** [comment]
sounds like a 500ml bottle should be fine then, although its not significantly more expensive to get 1L
https://uk.rs-online.com/web/p/precision-cleaners-degreasers/2274427/
