### ISSUE TITLE
[SP2019]Test Power Consumption of Kit

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#48]
Last year there was an issue with kit tripping over current protection. This year we should connect as much kit as possible together before the competition to find if this is going to be an issue again. @trickeydan would you be able to provide a list of exactly what should be connected.

**Comment by trickeydan** [comment]
- 1 Power Board
- 1 Motor Board
- 1 RasPi 3
- (with and without) 1 Servo Board
- Arduino with lots of ultrasound sensors

See [SB Docs](https://docs.sourcebots.co.uk) for more info about the kit.
