### ISSUE TITLE
[SP2019]Update docs with kit changes

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#49]
- [x] API Changes
    - [x] Hardware changes
    - [x] [sbot](https://github.com/sourcebots/sbot) / [j5](https://j5.org.uk/j5) if applicable.
- [x] Servo Board
- [x] Arduino
- [ ] Vision
- [x] Remove references to servo assembly,

**Comment by jcwilliamson** [comment]
- [ ] Image of motor under "basic movement"

**Comment by trickeydan** [comment]
Review pending. https://sbot.readthedocs.io/en/api-docs/

**Comment by trickeydan** [comment]
Done
