### ISSUE TITLE
[SP2019]Order Motor Mounting Brackets

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#54]
We are short on these. We need to order 25 of these from ECS Mech. Workshop.

**Comment by trickeydan** [comment]
At least a 5 week lead time on these. Should be ordered ASAP

**Comment by Dasepho** [comment]
If this needs an email sent from sro@soton.ac.uk, let me know and I can do so

**Comment by trickeydan** [comment]
> If this needs an email sent from [sro@soton.ac.uk](mailto:sro@soton.ac.uk), let me know and I can do so

The easiest way to sort these is to drop into the mech workshop in person.

**Comment by jcwilliamson** [comment]
I'd probably take an example down too, so they know exactly what we're
looking for.

**Comment by jcwilliamson** [comment]
Have these been ordered yet? If not, it needs doing soon. @trickeydan should I do this tomorrow? If I could get into the cupboard to grab one as an example piece, that would be great.

**Comment by trickeydan** [comment]
Yes let's do this tomorrow.

**Comment by trickeydan** [comment]
Waiting on a Quote

**Comment by Tyler-Ward** [comment]
We have 12 motors that will need new mounts next years expansion to 100 students will require an additional 10 this gives 3 spares (beyond the spare modules)

**Comment by jcwilliamson** [comment]
Update: mech workshop says that we will be getting these some time tomorrow. Total of 35 units

**Comment by jcwilliamson** [comment]
Picked these up from mech. Today.
