### ISSUE TITLE
[SP2019]Create ultrasound sensor modules

### ISSUE THREAD

**Issue by Tyler-Ward** [sourcebots/tasks#55]
It is worth investigating adding breakout boards for the ultrasounds with screw terminals to aid in robot assembly. If cheap enough we can get teams to assemble them as part of the electronics lab.

@jcwilliamson are you interested in looking at this?

**Comment by Dasepho** [comment]
Do the ultrasound modules not already have 0.1" headers on? Or are these just not as good as screw terminals?

**Comment by joe9599** [comment]
@Dasepho you dont necessarily want to connect the ultrasound directly where the board is, so having screw terminals means it is easy to connect anywhere, the breakout could also have mounting holes which would make it easier for teams to mount, I assume this just needs to be a 0.1" header to screw terminals, so wont need anything complicated, if we are ordering them I cant see it costing more than £20-£30 from jlc for 30ish boards. @Tyler-Ward Is this right or would the boards need more than header, terminals and mounting holes

**Comment by jcwilliamson** [comment]
I was thinking the same as @joe9599 0.1 female header on one end, some screw terminals on the other. I don't see a reason we'd need anything more complicated.

**Comment by trickeydan** [comment]
I've heard that @joe9599 has been working on this

**Comment by joe9599** [comment]
The boards are designed, and ready for prodcution

**Comment by trickeydan** [comment]
> The boards are designed, and ready for prodcution

Please could somebody work on getting these into the `s-r-o` github?

**Comment by joe9599** [comment]
I'll just double check them once more, then attempt to stick them on github

**Comment by joe9599** [comment]
@trickeydan Here is the files on Github, hopefully I did it right
https://github.com/s-r-o/Ultrasound-sensor-adapter

**Comment by kierdavis** [comment]
PCB looks good to me :+1:

**Comment by joe9599** [comment]
The board has now been updated to add mounting holes and replace the capacitor with a 100uF electrolytic capacitor as I have been told that this fixed some issues during last years smallpeice, the updates are checked into github

**Comment by trickeydan** [comment]
Is this done @joe9599?

Also, I am unsure why this is restricted to `soton`, please explain your labelling?

**Comment by joe9599** [comment]
I am just waiting for them to be approved and ordered.
I have labelled it as soton, as that is where would be easiest to assemble when the arrive (I am counting assembling as part of "creating") alternatively, they could be shipped to individuals to each assemble at their homes,  however I dont know who is going to have what capabilities at their houses, for example I can solder a small quantity (probably 20ish), but wouldn't be able to test them (and the soldering may not be as good as usual, as my soldering iron isn't great)

**Comment by trickeydan** [comment]
The boards have arrived and need building. Waiting on components.

**Comment by kierdavis** [comment]
Components have arrived. I think @Tyler-Ward is assembling some or all of these during the week. I'm happy to help finish them off next weekend if needed.

**Comment by Dasepho** [comment]
I'm in Soton from Thursday. Let me know if I can help

**Comment by kierdavis** [comment]
100 of these have been built.
