### ISSUE TITLE
[SP2019]Chase up remaining funds for summer school

### ISSUE THREAD

**Issue by Tyler-Ward** [sourcebots/tasks#56]
we should chase up the remaining budget

**Comment by trickeydan** [comment]
Son is going to do this

**Comment by trickeydan** [comment]
Waiting on quotes from @kierdavis

**Comment by trickeydan** [comment]
Had a meeting with Son and Joyce. 

Arranging meeting with Kier and Tyler to sort manufacturing.

**Comment by trickeydan** [comment]
This was chased and obtained
