### ISSUE TITLE
[SP2019]Assemble Motor Modules

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#6]

**Comment by jcwilliamson** [comment]
If possible, I'd like this to be done by someone with some experience. @Tyler-Ward @trickeydan @Dasepho (Dan, can you tag Joe if he's on here) this seems like something one of you might be able to do. If not, I'm happy to take this and #7 myself over the next couple of weeks.

**Comment by Dasepho** [comment]
@joe9599 see above ^

**Comment by joe9599** [comment]
I am good to do stuff from Friday afternoon if you need hands for this (although I dont have experience with these specific motor modules)

**Comment by trickeydan** [comment]
> I am good to do stuff from Friday afternoon if you need hands for this (although I dont have experience with these specific motor modules)

It's very simple soldering, even I can do it ;)

I'm available on Friday Afternoon

**Comment by jcwilliamson** [comment]
@joe9599 perhaps you and I should group this up with #43 and get it done in
one go. I'm free Friday too

**Comment by joe9599** [comment]
How long do we expect this, #7 and #43 to take?

**Comment by jcwilliamson** [comment]
I wouldn't expect more than a couple of hours to assemble and test 8 motors.

**Comment by joe9599** [comment]
In that case @Dasepho will you be around? it would be good to get all 3 tasks done in 1 go

**Comment by Dasepho** [comment]
I should be around and will be happy to help

**Comment by Dasepho** [comment]
Happy for me to assign myself, @jcwilliamson and @joe9599 ?

**Comment by Dasepho** [comment]
Done
