### ISSUE TITLE
[SP2019]Inventorise working kit

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#62]
Count the amount of working motor and power boards that we have.

This is primarily for #8

**Comment by kierdavis** [comment]
Based on an inventory we did a few months ago when deciding how much kit to manufacture, I think we have 8 working power boards and 9 working motor boards. I'm not certain if these numbers are still up to date.

**Comment by kierdavis** [comment]
@trickeydan did this last night and says he updated the [inventory](https://docs.google.com/spreadsheets/d/1C0oOGQNJ-7rAppNlEvt1zI5zew3wNtpBUpZjMcK-Ork/edit#gid=886293144) to match, but most of the boards are still listed as "unknown" status on there.

Dan, please could you confirm what the status of this is?

**Comment by trickeydan** [comment]
Have updated

I'm slightly uncertain about `SRO-AA4-7BO`, as it was marked as previously not working, but all of the boards I tested last night worked...

**Comment by kierdavis** [comment]
Thanks!

I count:
* 8 working power boards, as expected
* 9 working motor boards + 1 probably working (`SRO-AA4-7BO` as mentioned above)

I'd suggest stress-testing `SRO-AA4-7BO` a bit to see if any failures are observed; if not, lets assume it's working until further notice.

**Comment by PeterJCLaw** [comment]
Do we know how many batteries and chargers we have working?

**Comment by PeterJCLaw** [comment]
> Do we know how many batteries and chargers we have working?

Ah, just spotted that we apparently (https://github.com/sourcebots/tasks/issues/8#issuecomment-497327914) have enough.

**Comment by trickeydan** [comment]
This has been done
