### ISSUE TITLE
[SP2019]Order Scaff

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#63]
Blocked on https://github.com/sourcebots/tasks/issues/25

We typically order scaff from 'SGB a Brand Safway company'. There's an account set up with the university and we're grandfathered such that their 4 week minimum order time doesn't apply to us (which was probably set up especially because of us lol)

We typically order to arrive on the Monday of the week, and pick up on the Monday after. Instruct them to go to the loading bay of B42 but tell them to phone your mobile before delivery so you can direct them if needed.

Here's the quote for SR2019:
![scaff_quote_sr2019](https://user-images.githubusercontent.com/2551763/58668461-48d7fd80-8339-11e9-9af9-13190674bf49.jpg)

**Comment by Adimote** [comment]
This is blocked by confirming what scaff layout we're going for (pending a game decision)

**Comment by Adimote** [comment]
I believe this is unblocked as we're going for the 8mx8m arena

**Comment by joe9599** [comment]
I believe this should also include scaff for the tree

**Comment by trickeydan** [comment]
@joe9599

Why would we make the tree out of scaff?

I thought that the plan was wood / stage decking?

**Comment by joe9599** [comment]
I thought the upright was scaff, I may have misunderstood though

**Comment by WillB97** [comment]
In #73 we were talking about using truss which susu already has.

**Comment by Adimote** [comment]
I'm happy to arrange this

**Comment by Adimote** [comment]
First email sent, we should get a quote in response, which we then accept and put in a purchase order through the uni

**Comment by RealOrangeOne** [comment]
A fallback for this might be to use the SR wooden arena, although we'd need to enquire about this before hand.

This would also require hiring crowd barriers

**Comment by Adimote** [comment]
I didn't get any positive answers from my initial round of emails, I'll be calling some companies tomorrow

**Comment by trickeydan** [comment]
If some other people could call too that would be great.

I'll try and call a couple in my lunch hour tomorrow

**Comment by Adimote** [comment]
Here's my list of contacted companies: https://docs.google.com/spreadsheets/d/1-gv1YSWaeBx_7S25lZgV1eRCUk9zXO_WWbuwcwbT7KU/edit?usp=drivesdk best to just check I haven't contacted them already

**Comment by Adimote** [comment]
Ooh also I've got a model set of things to ask for on the other tab of the sheet

**Comment by Adimote** [comment]
Here's a quote from RBS Scaffolding: https://drive.google.com/file/d/1-dcF07SXbPdZGoA4ZSdNrxtN_1JpbnUG/view?usp=drivesdk total is £674

**Comment by trickeydan** [comment]
Ok that's significantly higher than we budgeted for I think. @Tyler-Ward can you confirm? I think it was £400ish in the budget based on last year.

**Comment by Tyler-Ward** [comment]
we spent around 176 last year

**Comment by Adimote** [comment]
Just got the first quote for regular ol' scaff: 

24 x 8’ tube            £192.00
22 x 16’ tube          £352.00
6 x 21’ tube            £126.00
14 jacks                   £112.00
14 baseplates         £14.00
75 swivel couplers   £75.00
Load and delivery to site   £50.00
All prices are subject to vat @ 20%

So total is £921 excluding VAT, That's frankly rediculous

**Comment by Adimote** [comment]
Sadly I haven't been able to order scaff for the competition this year :<
