### ISSUE TITLE
[SP2019]Risk Assessments

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#64]
We need to check and update these.

Especially with the larger number of students.

**Comment by kierdavis** [comment]
I can take a look at this. I've been meaning to tidy up the template anyway.

**Comment by kierdavis** [comment]
Is there a particular time that these need to be finalised by?

**Comment by trickeydan** [comment]
Before the summer school ideally ;)

**Comment by trickeydan** [comment]
Son is handling these this year.
