### ISSUE TITLE
[SP2019]Plan competition lighting

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/tasks#65]
The arena should have lighting which builds an exciting atmosphere. Obviously if we do ship a vision system (#9) then we need to account for that in the plan too.

**Comment by WillB97** [comment]
This would likely use a similar wash setup to the recent Student Robotics competition.

When we tested the libkoki vision system with this lighting we did not find any reasonable scenarios where tokens couldn't be read, although some teams did still report issues.
