### ISSUE TITLE
[SP2019]Plan competition audio setup

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/tasks#66]
The arena venue should have a sound configuration which builds an exciting atmosphere.
That being said, the pit areas should be quiet to allow people to get things done.

The finals likely want something a little different to the main matches.

**Comment by WillB97** [comment]
Separate music levels can be set between the cube and Bar 2, although there needs to be clear communication of what is wanted as there was a lot of conflicting information given at the recent competition.

**Comment by RealOrangeOne** [comment]
Having no audio in the pits at all is a little dull, but I think having something *very* quiet as background noise should be fine. We definitely want it loud in the cube, though!

The playlists for both in and out of match are currently in progress, based off the works from previous SR / SB / smallpeice events. 

[In Match](https://open.spotify.com/user/theorangeone97/playlist/3P9ptA4qEqHCIMkLaVsE5h?si=lfA4BfISSa6fwIp7Fu3fcg)
[Out of match](https://open.spotify.com/user/theorangeone97/playlist/3LOLCboS4JB25xJDjj2VsA?si=fyNNMNZcRIatDqda2xCl6g)

I'm happy to own those playlists, and providing a device to run them off, based on the assumption of a 3.5mm jack, an upstream internet connection, and power.
