### ISSUE TITLE
[SP2019]Plan league matches

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/tasks#68]
We need to know how the league matches will work - which teams will face which other teams along with timings.

This may be able to be similar to previous years, however with the increase in teams (to 16) it won't be exactly the same.

See also #51 (compstate).

**Comment by PeterJCLaw** [comment]
@prophile could you run your league scheduling solver thingy for 16 teams and spit out a schedule?

**Comment by sedders123** [comment]
These have been planned https://github.com/sourcebots/compstate-smallpeice2019/blob/94e486f579729bd9ec02a2439b433fe2992e7cc6/league.yaml

**Comment by PeterJCLaw** [comment]
While the match arrangement is done, the timings are not yet sorted.

**Comment by PeterJCLaw** [comment]
timings have now been sorted.
