### ISSUE TITLE
[SP2019]Plan knockout matches

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/tasks#69]
We need to know how the knockout matches will work - which teams will face which other teams along with timings.

This may be able to be similar to previous years, however with the increase in teams (to 16) it won't be exactly the same.

See also #51 (compstate) and #67 (finals production).

**Comment by PeterJCLaw** [comment]
Since 16 is a power of 2 I think we should just use the automatic knockout support within SRComp. The main reason we've not done that in the past is that it's not great at ensuring fair setups around byes, however I'm reasonably confident it's fine if you have a power-of-two number of teams.

**Comment by sedders123** [comment]
These have been planned https://github.com/sourcebots/compstate-smallpeice2019/blob/5da2211dbeb3d2a0e591efc539d4087fb7f22d27/schedule.yaml

**Comment by PeterJCLaw** [comment]
While the match arrangement is done, the timings are not yet sorted.

**Comment by PeterJCLaw** [comment]
timings have now been sorted.
