### ISSUE TITLE
[SP2019]Organise in-venue screens

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/tasks#70]
We typically have screens in the venue displaying information about the state of the competition for various purposes.

- match staging
- general information

This is a high level task to cover planning what we show where as well as organising the hardware and any software configuration. It is encourage that details either be added as checklist items or as subtasks (or possibly both).

**Comment by jcwilliamson** [comment]
Would it be worth going to b16/59 labs for these? They gave them to us for SR, I don't see why they wouldn't be willing to again.

**Comment by trickeydan** [comment]
Yeah definitely

**Comment by WillB97** [comment]
Working out where we want the screens is the main restriction on deciding the level of networking that is required.

**Comment by Adimote** [comment]
about to send one email to Dave Oakley about all things we want to borrow (laptops, screens, and trolley)

**Comment by tshoang** [comment]
@Adimote Have you discussed with Dave regarding these issues?

**Comment by Adimote** [comment]
Yes I sent an email to Dave oakley

**Comment by PeterJCLaw** [comment]
Regarding placement, here's what I'm currently assuming:
- four in the arena corners (modulo some shenanigans around #150 and the possible lack of scaff)
- one by the staging area for the badger (probably mounted on the arena if possible, modulo #150)
- two general information screens, just inside and outside the Cube doors respectively

For networking this is mostly easy -- run long cables from the balcony. The one outside the Cube is a bit more of a faff. If that's a Pi 3 then WiFi is an option, though I'd rather have a cable. The cable does mean we'll need to configure some non-trivial networking, but it's doable.

@Adimote are you owning sorting the hardware (both drivers and connections) for this?

**Comment by PeterJCLaw** [comment]
Hardware:
- we apparently have plenty of network cabling
- we have 6 display driver Pis with PSUs, SD cards & mounts
- SUSU will be providing power distro (cc #85)
- SUSU will be (hopefully) providing the _large_ screens (cc #85)
- ECS will be providing the normal sizes screens (we need at least 5)

**Comment by Adimote** [comment]
Prodded Dave Oakley because he's terrible at replying to emails

**Comment by Adimote** [comment]
Dave replied with a 'We probably don't have them, will check tomorrow', to my email which asked for many things, at a best guess he was probably referring to the screens, so we likely need to scrounge together screens from elsewhere

**Comment by trickeydan** [comment]
@jcwilliamson is going to ask Jules if we can borrow a couple from the pile.

**Comment by Adimote** [comment]
Got confirmation that Dave Oakley won't be giving us any screens

**Comment by PeterJCLaw** [comment]
Display screens are very much hireable; is it worth looking into that? (i.e: do we have budget capacity?)

**Comment by trickeydan** [comment]
This should be a last resort as we're going to be over budget on scaff if we get it.

Also the budget has closed. We shouldn't be getting anything else now.

There is a huge pile of new monitors that Jules has bought and hopefully we might be able to borrow some. We'll hopefully know what the next steps are on Monday.

**Comment by tshoang** [comment]
@trickeydan is right, the budget has closed (I'm afraid that there already are few things spilled over).

**Comment by PeterJCLaw** [comment]
I had a very quick look online for hire costs, but the places I found all involve calling them up to get a quote :disappointed:, so I'm assuming we'd need to wait until Monday anyway.

**Comment by PeterJCLaw** [comment]
I may be able to borrow some of these I've got an agreement in principle for 5, though it depends how many are actually available.

**Comment by Adimote** [comment]
I've email Jules very kindly to ask about borrowing from his supply

**Comment by Adimote** [comment]
I got an auto-reply saying he's doing half-time, might take some time to reply

**Comment by Adimote** [comment]
Jack tried to contact him in person today and failed. I guess Jules is being deliberately inaccessible. Our backup plan was to scrounge together some screens, but @PeterJCLaw pointed out quite obviously that we could just borrow SR screens (thanks Peter!)

We've contacted Diane, and she says it should be fine, Yay!

**Comment by tshoang** [comment]
> Jack tried to contact him in person today and failed. I guess Jules is being deliberately inaccessible. 

 Jules is trying very hard to take holiday (from his auto-reply). I'm glad that it is resolved.
