### ISSUE TITLE
[SP2019]Organise competition operations

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/tasks#71]
In order to sync up the screens (#70), lighting (#65) and audio (#66) we'll need a network and likely a deploy of [SRComp](https://github.com/PeterJCLaw/srcomp/wiki). These will be driven by a compstate (#51).

This is a high level task to cover planning as well as organising the hardware and any software configuration. It is encourage that details either be added as checklist items or as subtasks (or possibly both).

**Comment by WillB97** [comment]
All the isolutions sockets in Susu are fully routable from each other so simpler solutions than previously used could be deployed.

The most significant factor is what systems need to be connected to the network outside the cube

**Comment by PeterJCLaw** [comment]
Hardware:
- screens are covered (see https://github.com/sourcebots/tasks/issues/70#issuecomment-515699015)
- I'm happy to use my Pi 3 as the compbox

It would be handy to have a monitor for the compbox machine, though non-essential.

I'll probably also configure a public facing compbox as I have in the past.

**Comment by PeterJCLaw** [comment]
Deployment plan:
- compbox: my Pi 3
- arena corners: four SB Pis
- staging: SB Pi
- large display just inside the Cube: my Pi 2
- large display just outside the Cube: SB Pi

**Comment by PeterJCLaw** [comment]
We're ready to go here.
