### ISSUE TITLE
[SP2019]Build 'market stall' scoring zones

### ISSUE THREAD

**Issue by Dasepho** [sourcebots/tasks#75]
Each team has a raised platform "market stall" on which to put apples they collect for more points. Likely to be very basic MDF/screws construction

**Comment by joe9599** [comment]
I am currently designing this, but will need someone in Soton to laser cut it

**Comment by Dasepho** [comment]
I can laser cut it if we can get material from mech workshop

**Comment by joe9599** [comment]
here are the proposed files to be laser cut
[separated into sheets.zip](https://github.com/sourcebots/tasks/files/3273503/separated.into.sheets.zip)

**Comment by Dasepho** [comment]
![Screenshot at 2019-06-11 09-08-50](https://user-images.githubusercontent.com/47758255/59255567-32c81800-8c2a-11e9-983f-92ca12104fcd.png)

**Comment by Dasepho** [comment]
We're considering this blocked by #81 for now

**Comment by joe9599** [comment]
Here is the 2d flat pack which fits with the above 3d model
[separated into sheets.zip](https://github.com/sourcebots/tasks/files/3276338/separated.into.sheets.zip)

**Comment by joe9599** [comment]
not doing appletree
