### ISSUE TITLE
[SP2019]Glue motor connectors to the back of the motor mounts

### ISSUE THREAD

**Issue by Tyler-Ward** [sourcebots/tasks#77]
This will reduce the damage to the connectors.

**Comment by jcwilliamson** [comment]
This could probably be done the weekend before, it doesn't seem like a long job.

**Comment by trickeydan** [comment]
@Tyler-Ward has ordered a *LOT* of glue apparently.

**Comment by Dasepho** [comment]
I'll take this if I can get the glue and the motors

**Comment by Dasepho** [comment]
Done
