### ISSUE TITLE
[SP2019]upgrade tudor motors

### ISSUE THREAD

**Issue by Tyler-Ward** [sourcebots/tasks#79]
The 3 motors on one tudor need upgrading with mounts and connector boards

**Comment by jcwilliamson** [comment]
I've got the motors out still, so would be happy to do this. This will require additional camcons and possibly more capacitors.

**Comment by jcwilliamson** [comment]
These have now been added to the order list.

**Comment by trickeydan** [comment]
This was done for the Denis weekend
