### ISSUE TITLE
[SP2019]Obtain Kit from SR

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#8]

**Comment by trickeydan** [comment]
We don't have enough kit. SR agreed a kit loan.

**Comment by PeterJCLaw** [comment]
We'll need to put together a list of what it is we'd like to borrow from SR; is that part of this ticket, or done somewhere else?

**Comment by trickeydan** [comment]
> We'll need to put together a list of what it is we'd like to borrow from SR; is that part of this ticket, or done somewhere else?

That should probably be a separate ticket imo. I'll create one for it.

**Comment by kierdavis** [comment]
I presume that the amounts of power/motor/servo boards we intend to borrow is the same as the amounts we intend to manufacture ourselves; that is,

* 17 power boards
* 16 motor boards
* 25 servo boards

EDIT: Oops, just saw you've created a separate issue for this.

**Comment by kierdavis** [comment]
Other things we may or may not need to borrow (I don't know):

* USB hubs
* USB cables
* Camcons
* Webcams
* Batteries
* Battery bags
* Battery chargers & power supplies

**Comment by trickeydan** [comment]
>     * USB hubs
>     * USB cables
>     * Camcons
>     * Batteries
>     * Battery bags
>     * Battery chargers & power supplies

We're good on these. Have ordered more / have enough already.

>     * Webcams

This is an interesting question, as for #9 we will probably want to use known good webcams.

They may be in budget, but I am unsure.

**Comment by trickeydan** [comment]
We have bought enough webcams now.

Do we need to make a formal request for this?

**Comment by Adimote** [comment]
Any update on this? From what I've heard, a formal request was made

**Comment by trickeydan** [comment]
A formal request was made. The reply requested money, so we explained how our funding works. Another reply said that we probably wouldn't need to pay and I've heard nothing since.

**Comment by Adimote** [comment]
Ah that's good news! We should probably prod them though to make sure the kits are shipped soon

**Comment by Adimote** [comment]
Jake will prod the SR trustees

**Comment by RealOrangeOne** [comment]
We should get an answer on this Thursday evening, as this is when the trustees will be meeting.

**Comment by RealOrangeOne** [comment]
The trustees have agreed to loan the kit, for free, pending the signature of a loan agreement, and a list of the specific items required (and quantities, obviously).

As the email was addressed to @trickeydan, and the loan agreement is between SRO and SR (whether this is correct is a discussion for some other day), I defer the final execution of this ticket to @trickeydan.

**Comment by trickeydan** [comment]
The contracts were posted by tracked royal mail on Tuesday, but I have yet to hear if they have been received.

**Comment by RealOrangeOne** [comment]
I've chased this up with Diane.

**Comment by RealOrangeOne** [comment]
I've received confirmation from Diane that whilst the loan agreement hasn't been received yet (which is odd), she's happy for the kit to be loaned.

(Proof available upon request)

**Comment by kierdavis** [comment]
Has transporting the kit been organised yet?

**Comment by trickeydan** [comment]
I don't feel like this ticket should be assigned to me any longer. Communication has been taken over by @Adimote and @RealOrangeOne afaik.

**Comment by RealOrangeOne** [comment]
This has *not* been taken over by me! I simply confirmed whether we were ok to proceed with the loan agreement in-transit.

As the loan agreement is between SRO and SR, it makes sense for someone from SRO to be the task owner on this side. Re-assigning @trickeydan until another owner is allocated.

**Comment by trickeydan** [comment]
I am unassigning myself as this was *taken over* and I do not know the state of things anymore.

**Comment by sedders123** [comment]
@RealOrangeOne and @PeterJCLaw Have been to the container and obtained the required kit.
