### ISSUE TITLE
[SP2019]Write formal rules document 

### ISSUE THREAD

**Issue by Dasepho** [sourcebots/tasks#81]
Turn game proposal into formal rules for teams, has to be in a private repo but keeping an issue here for it for tracking progress purposes

**Comment by PeterJCLaw** [comment]
This feels like a silly question, but why does this need to be in a private repo? The game design is already public (see #25 and #75), so it's not like there's any suspense to be gained by having the precise details kept private.

**Comment by Dasepho** [comment]
That's a good point. My concern is that we could have a 'perceived fairness' problem if some students know the game in advance and strategise. That ship might have already sailed as you point out with #25 and #75.
That said, at the moment all public knowledge is subject to change but the final rules document won't. I guess any students that see #25 and #75 know they are working with incomplete / inaccurate info so at the very least this is less likely to cause the other students to feel cheated. There are also some details that are tbd since #25 are likely to significantly impact strategy.
It's entirely likely that this could be public without issue, but I think it's easier for us to demonstrate to teams that we're trying to ensure a fair competition if we make an effort to keep the details private until formally announcing the game.

**Comment by trickeydan** [comment]
> This feels like a silly question, but why does this need to be in a private repo? The game design is already public (see #25 and #75), so it's not like there's any suspense to be gained by having the precise details kept private.

I think this is a fair point. I made the rules repo private without knowing that we had already published it in a public area.

I'm happy to move the rules repo to the SourceBots Org if we are going to have it public.

**Comment by Dasepho** [comment]
When have the rules been announced in previous years? If they are announced at the start of the week then I imagine it wouldn't give an unfair advantage to anyone who sees them ahead of time.

**Comment by joe9599** [comment]
I believe this is now blocked on figuring out cube manufacture, as that may lead to a variant of the game, or a completely different game all together blocked on #82

**Comment by Dasepho** [comment]
I'm happy to go through the document in the next few days. Is there a link to the doc from last time around?

**Comment by Dasepho** [comment]
Suggestion of modifying the arena for the game this time. Discussion to be done at Hackday weekend, blocking writing of the final doc.

**Comment by trickeydan** [comment]
![image](https://user-images.githubusercontent.com/7862359/61996038-d01ac680-b087-11e9-8ecf-c43e4e54f609.png)

## _Scavengers_

- Robots start as usual in starting zones. Orientation and position inside the starting zone can be specified by competitors.
- Teams must get tokens placed in pseudo-random locations into their allocated scoring zones.
- For each token in their scoring zone, a team gets 2 points.
- For each token in the raised central area, tokens are worth 5 points.
- The scoring zones will be bounded by metallic tape around the perimeter and internal boundaries
- The arena will have 28 tokens (7 per team) in the arena
- Define 4 patterns for marker layouts in the arena (outside scoring zones) (much like Pirate Plunder from 2018), we pick 2 per league, and place tokens on them (12 possible layouts)
- 1 token will be placed in front of each robot, equidistant between the edge of the robots starting zone, and the scoring zones.
- Scoring zones will be offset 90 degrees per team (see diagram)
- Tokens must have 3 corners in a scoring zone to count. As the raised area is inside the scoring zone, tokens not quite in the raised area will be in the main scoring zone
- Tape doesn't count as inside either scoring zones bounding it. Scoring zones are defined by the inside edges of the bounding tape

I (@RealOrangeOne) invite input from @prophile on this, before I write the draft formal rules spec. (Ideally plan to write before the next hack day)

**Comment by trickeydan** [comment]
~Argh more usage of my account!~

**Comment by RealOrangeOne** [comment]
Feedback from @prophile:

- Points for climbing the raised area?
- 16 tokens
- 25mm tokens
- Wall between sections of the arena
- 9x9 arena
- 3m central area

The final 2 are pending a new 9x9 scaffolding arena, to be handled by #150, hopefully.
