### ISSUE TITLE
[SP2019]Confirm ECS can provide items we previously borrowed from them

### ISSUE THREAD

**Issue by Tyler-Ward** [sourcebots/tasks#84]
The list according to the equipment list is

* Hacksaw - Junior
* Hacksaws
* Hot glue gun
* Panel/Crosscut Saws
* Hand Powered Drills
* Set Squares
* Hookup Wire
* soldering irons

**Comment by trickeydan** [comment]
Who do we need to talk to about this?

**Comment by Tyler-Ward** [comment]
Someone needs to pop down to L2 labs and ask

**Comment by trickeydan** [comment]
Essentially yes. They are concerned about the number of students though. We need to talk to Dave apparently but he wasn't in.

**Comment by Tyler-Ward** [comment]
@trickeydan is there any more that needs to be done for this

**Comment by trickeydan** [comment]
I think we can close this
