### ISSUE TITLE
[SP2019]Arrange for SUSU tech hire

### ISSUE THREAD

**Issue by Tyler-Ward** [sourcebots/tasks#85]
We should talk to susu to hire the kit we need again

**Comment by trickeydan** [comment]
We should try and do this before the end of June in order to get it out of the way.

We will have much less resources in July.

**Comment by WillB97** [comment]
Is this also going to include purchasing carpet or are we using the roll from last year?

**Comment by trickeydan** [comment]
#141 will cover this

**Comment by RealOrangeOne** [comment]
This was covered in #141
