### ISSUE TITLE
[SP2019]Pick up laptops

### ISSUE THREAD

**Issue by Tyler-Ward** [sourcebots/tasks#86]
We need to borrow laptops for use in the cube previously this has been from Jules

**Comment by trickeydan** [comment]
Does Jules have 16 laptops?

We may have to borrow some from Jules and some from L2 labs

**Comment by trickeydan** [comment]
Have spoken to Jules today. Booked out possibly 10, but that is all that he has.

**Comment by Adimote** [comment]
about to send one email to Dave Oakley about all things we want to borrow (laptops, screens, and trolley)

**Comment by tshoang** [comment]
@Adimote Any reply from Dave?

**Comment by trickeydan** [comment]
14 laptops have been arranged from isolutions and will be picked up by @jcwilliamson on Monday.

**Comment by trickeydan** [comment]
We will still need a few more from Jules, but that has already been set up

**Comment by Adimote** [comment]
Nice! Thanks for arranging this!

**Comment by kierdavis** [comment]
We went to pick them up today but were told that they hadn't been collected in time and they have been returned to stock. The earliest we can get them now is Monday afternoon. None of us were made aware that there was a time limit on the collection of the laptops.

**Comment by tshoang** [comment]
@kierdavis That's really something unexpected. What is consequence of this to the preparation? Is there anything that we can do to reduce the impact of this?

**Comment by trickeydan** [comment]
> @kierdavis That's really something unexpected. What is consequence of this to the preparation? Is there anything that we can do to reduce the impact of this?

This will be annoying, but if we can get them on Monday it should be ok. Students will have to use machines in the labs until then, which will not have our software autosuggestions working.

We could add instructions to the [kit docs](https://kit.sourcebots.co.uk) on how to add the type hints to Pycharm possibly.

**Comment by Tyler-Ward** [comment]
I don't believe they will be using the laptops till Thursday when they are in the cube as they will be using lab machines while they are based in labs.

**Comment by trickeydan** [comment]
The lab machines don't seem to have the software we want on them!

- Python 3.6.0 is installed, but no IDE.

**Comment by Tyler-Ward** [comment]
This is a problem as we need one machine per student (or at least one per pair) for the programming labs.

**Comment by joe9599** [comment]
> The lab machines don't seem to have the software we want on them!
> 
> * Python 3.6.0 is installed, but no IDE.

Is that no specific IDE or no IDLE

**Comment by trickeydan** [comment]
> Is that no specific IDE or no IDLE

They do not have an IDE for python. IDLE doesn't have the feature that we need.

Any recent version of PyCharm or VSCode would suffice

**Comment by tshoang** [comment]
I am going to meet Jeff McCann on Monday morning. The Programming Lab is on Tuesday. Do you think that he can help with any of this?

**Comment by kierdavis** [comment]
We've got 16 laptops from isolutions. We need to boot them up, check we can log in, and install pycharm.
