### ISSUE TITLE
[SP2019]Ensure content is accessible

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#91]
We have received the following requirements to enable a student this year:

“[REDACTED] would appreciate any written material provided electronically so that she can access it on her laptop in a format that suits her. If you are able to provide any powerpoints on a USB at the time of presentation that would be helpful.
She may need to ask for additional help with practicals especially if dealing with small components but she has recently taken part in the Student Robots competition run by Southampton University and had no problems accessing both hardware and software aspects so she does not anticipate significant problems with accessing the course.”

**Comment by RealOrangeOne** [comment]
Ensuring content is available electronically is generally a good idea anyway, as it saves distribution. 

I'm happy to own ensuring any presentations are available, _somehow_. Likely through links on the docs.

**Comment by RealOrangeOne** [comment]
I've created a public folder in the SP2019 drive folder, which can be used to public files as necessary.

The Public share link (read only): https://drive.google.com/drive/folders/1RsuZ5gVOAb6NWUDxjrXn0hPvp-PP9Kre?usp=sharing.

Any slides created by us can be entered into there shortly before the presentation. We will need to reach out to lecturers to provide their slides. 

This link can be used by any student to re-view our slides as needed.

**Comment by kierdavis** [comment]
I think everything listed in #115 needs to end up in that folder.

**Comment by trickeydan** [comment]
This has not been done adequately. The student was not given the presentations in time for Jenny's talk, and there no presentations for the other talks.

**Comment by JennyLouise** [comment]
@trickeydan I should have kept that business card with Jon's email on it, can you send it to me and I'll forward him the link. And we need everyone's presentations, I'll follow people up on that

**Comment by JennyLouise** [comment]
@tshoang - do you have any documents that need adding to the shared folder, like from your housekeeping talk yesterday, or any other presentations? Could you also ask Jon and Dennis for their presentations prior to their slots? They can email them to me at jenny.walker@soton.ac.uk

@trickeydan @RealOrangeOne (& @ Andy Busse - but I can't seem to actually tag him) - can I have the how to build your robot presentation? And any others you think would be useful to provide in the shared folder

**Comment by trickeydan** [comment]
I don't think we are shipping any more content, so this can be considered done.
