### ISSUE TITLE
[SP2019]Send Python Worksheets

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#92]
We need to send any worksheets out ASAP.

**Comment by Adimote** [comment]
Typically this is a generic 'introduction to python' worksheet, normally we update the old 'Python: A Whirlwind Tour' and send it out: https://github.com/s-r-o/python-a-whirlwind-tour

**Comment by trickeydan** [comment]
We need to get a license put on this..

**Comment by Adimote** [comment]
I agree, it would be useful to put a license on it so other people can use
it without worries. I don't think it's blocking us modifying & sending it
out though.

**Comment by RealOrangeOne** [comment]
SourceBots already has a sufficiently licensed version of the whirlwind tour on the docs (https://docs.sourcebots.co.uk/tutorials/python-whirlwind-tour/). It might be worth removing that repo to avoid confusion.

Given https://github.com/sourcebots/tasks/issues/103#issuecomment-511142183, do we need worksheets?

**Comment by trickeydan** [comment]
Have sent pdf to Son for distribution.

**Comment by RealOrangeOne** [comment]
Said PDF, for reference: [sourcebots_whirlwind.pdf](https://github.com/sourcebots/tasks/files/3391237/sourcebots_whirlwind.pdf)
