### ISSUE TITLE
[SP2019]Arrange for guest accounts

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#94]

**Comment by jcwilliamson** [comment]
Has this been done yet? Or do we still need to email Isolutions

**Comment by trickeydan** [comment]
Son is on it, hence the `ECS` label

**Comment by trickeydan** [comment]
I have prodded Son

**Comment by tshoang** [comment]
A request has been raised with iSolution (with highest priority). Waiting for their reply.

**Comment by tshoang** [comment]
For the record, the guest account can be ordered (by University members) at the following website (which I did)
https://www.southampton.ac.uk/isolutions/forms/accounts-for-conference-visitors.page

**Comment by tshoang** [comment]
Done. I have obtained 100 guest accounts from iSolutions for the week.

**Comment by trickeydan** [comment]
Thanks Son.
