### ISSUE TITLE
[SP2019]Arrange with Estates to move things between venues

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#95]
We'll be generating a list of things which we want them to move (#125), this is about arranging for the movement to happen.

**Comment by trickeydan** [comment]
Kajetan is prodding Son

**Comment by tshoang** [comment]
Can I please have the concrete plan of where and when things need to be moved?

**Comment by kierdavis** [comment]
Blocked on #125.

**Comment by tshoang** [comment]
I have contacted Estates and have a meeting with someone tomorrow (Thursday) afternoon to show them the L4 Storage to make sure that there will be no surprise on Monday. Please let me know if any other equipment that need to be moved.

**Comment by trickeydan** [comment]
> I have contacted Estates and have a meeting with someone tomorrow (Thursday) afternoon to show them the L4 Storage to make sure that there will be no surprise on Monday. Please let me know if any other equipment that need to be moved.

The wood in the L4 storage is mostly behind all of the boxes (large sheets of wood) and to the right side of the cupboard. When we run the summer school, pretty much the entire cupboard is emptied, although a fair proportion goes to labs.

**Comment by tshoang** [comment]
All went well and the move on Monday morning is all set. The porters start 8am and have their tea break at 10am. All the equipment that need to move from B53 to SUSU need to be in one place (no labels are needed). Base on these requirements, here are some options to consider.
- Start the move from 8am. Need to prepare for the move, e.g., make sure all equipment in one place slightly earlier. If everything goes well, the move might be finished before the 10am tea break.
- Start the move from 9am. Again, some preparation will be required before 9am. However, it is likely to be over the tea break.
- Start the move after the tea break (10:30). There will be more porters available at that time and the move might be quicker. It gives more time in the morning to prepare for the move as well. But it might be too late (noon) to finish.
 Please let me know what you think. I need to confirm the start time with the porters.
Son

**Comment by trickeydan** [comment]
Starting the move at 8am works best for us.
